- Makefile
- global_config.h
- main.c
- uart_raw.c
- uart_raw.h
Since UART is probably going to be very useful for debugging, I moved raw access implementation to a separate file, cleaned it up a little bit, and added few convenience procedures.
`uart_raw.h` provides a simple interface for basic UART operations.
The `Makefile` is modified so that it supports compiling multiple translation units.
> Separated raw UART interface

- Makefile
- main.c
- pic32mz.ld
- startup.S
- startup.s
Moved `_start` to `startup.s`. The start procedure now copies `.data` to RAM, and clears `.bss`. Renamed `main()` to `kernel_main()`. 
Fixes #2.
> Reorganized startup procedure as specified in #2.

- Makefile
- clock.c
- clock.h
- global_config.h
- interrupts.c
- interrupts.h
- intr.S
- main.c
- pic32mz.ld
- startup.S
This branch introduces initial support for interrupt configuration and handling.
It uses a single interrupt handler (vector spacing = 0), as discussed per #8. The core timer is configured to emit a high-priority interrupt every millisecond. The handler stores register status on the stack, and then calls a C procedure, which recognizes interrupt type and processes it. In case of a core timer interrupt, it increments a millisecond counter. That counter is used to implement mdelay which blocks execution until that counter reaches desired value. kernel_main uses that function in the main loop, and reports the elapsed time (in ms) since it started.
In this implementation nested interrupts are unavailable. Should I enable them already?
[Note: This branch is a clone of `core_timer` with fixed …
> Initial interrupt support, core timer interrupts

- Makefile
- include/common.h
- include/kmem.h
- include/libkern.h
- kmem.c
- main.c
- smallclib/Makefile
Implemented a bootstrap memory allocator as suggested in [this comment](https://github.com/cahirwpz/wifire-os/pull/17#issuecomment-168301900). The implementation is similar to [LiteBSD's](https://github.com/sergev/LiteBSD/blob/master/sys/mips/pic32/pmap.c#L181).
I was unsure to which namespace the allocator shall belong, so I ended up using `vm`.
Currently, allocating more than ~4000B will crash the kernel due to #25. However, the currently proposed fix for #25 solves the issue.
> Implemented early dynamic memory allocation

- Makefile
- context.S
- include/context.h
- main.c
Linked to #9.
The interface defined in `context.h` is pretty straight-forward. The `demo_ctx` I temporarily added to `main.c` is probably fancy enough.
I do not like the name of the main structure `ctx_struct` though, but I did not want to name it `ctx` or `context`. Any thoughts?
> Context switching

- interrupts.c
- intr.S
Look at title for more description.
@cahirwpz Please review this code. I'm bad assembly programmer, so I'd rather make sure everything works, before this goes to repo.
Besides I think irq_handler asm code can be simplified and we can directly jump to proper functions. I guess it is enough to mark proper functions with ((interrupt)) attribute. For example we could remove entire 'irq_handler' label in intr.S and then mark hardclock with ((attribute)), and other functions aswell. Note that there are more awesome properties of attributes, for more information check here: 
https://gcc.gnu.org/onlinedocs/gcc/MIPS-Function-Attributes.html
> ge_table is now array of addresses

- .clang_complete
- .gitignore
- Makefile
- Generating emacs-style tags file
- Added emacs backup files to gitignore
- Created a minimal .clang_complete which specifies standard and include
dirs for autocompletion and on-the-fly compilation checks
> Improved emacs integration

- launch
- Optional flag -D selects the gdb frontend to run in debug mode.
- Currently recognized values are gdb, cgdb, gdbtui, emacs and ddd.
- The default behavior of the launch script is unmodified.
> Selectable debugger in launch script

- include/mips/tlb.h
Hello
I'm using your platform as a reference in my own hobby educational OS and I've found this typo while debugging..
It seems to cause pmap_map() to fail invalidating TLB entries and this affects mapping a PFN1 page while PFN0 is already mapped or the other way around.
> Fixed TLB entry not invalidated due to bad asid mask

- mips/tlb_ops.S
tlb_overwrite_random() assumed to be given a forth argument to write to C0_PAGEMASK
but C function declaration did not reflect this argument and was called without it.
the PageMask register might be overwritten with garbage data
> Fixed C0_PAGEMASK garbage values in tlb_overwrite_random()

- mips/exc.S
The status register SR_KSU bits are: 0 for kernel, 1 for supervisor, 2 for user
Before this commit, user_exc_enter() 'turned off' the kernel-bits instead of the user-bits
> Fixed wrong bitmask in status register in user_exc_enter()

- README.md
- mips/boot.S
QEMU does not like c0_errpc and freaks out
Please report if this breaks your non-qemu emulator.
And if its does, we'll need to think if we want to solve this in different compilation targets or in startup runtime.
> boot: use regular jr to transfer control to kernel_boot instead of eret

- include/elf/elf32.h
- include/elf/elf_common.h
- include/elf/elf_generic.h
- include/elf/mips_elf.h
These headers define structures, symbols and constants that follow the ELF file format specification.
They were copied from FreeBSD SVN (as of 22 X 2016). Since they implement an old, solid standard, they were almost unchanged for 18 years, and we will not have to update them in the future.
> Imported headers with ELF type definitions from FreeBSD svn

- stdc/Makefile
- stdc/smallclib/string/strcmp.c
This is fairly straightforward. This branch expands the set of basic functions we import from SmallCLib to include `strcmp`.
I came to need this function at 9861491 in `elf-playground`. Basically, if we intend to include multiple ELFs embedded in the kernel image, it will be handy to be able to refer to them by their name, so that `exec` interface can take a string ("path to file") as its argument.
This implementation of `strcmp` is very simple, has no dependencies. Including it has no impact on our existing sources.
> Imported strcmp from smallclib

- include/mips/pcpu.h
- include/pcpu.h
- mips/exc.S
- mips/genassym.c
- mips/switch.S
- mips/thread.c
- sys/Makefile
- sys/pcpu.c
- sys/startup.c
Initial proposal for the implementation of the pcpu_t structure used to hold global cpu state
* Used sys/mips/include/pcpu.h and sys/sys/pcpu.h as reference.
* Implemented both C and ASM api macros.
* In the future this will hold per-cpu cpu state, for now its a simple global cpu state structure.
* As of now, only `current_thread` is held in pcpu_t.
> Introduced pcpu_t structure to hold global cpu state

- include/mips/mips.h
- include/pmap.h
- include/vm_map.h
- mips/pmap.c
- pmap.c
- sys/vm_map.c
- vm_map.c
While working on changing vm_map for user threads i realised it is better to keep asids away from interface. In future, when we have processes we might want to create asid or pid allocator, but for now simple incrementation until we run out of asids should be enough.
> Remove asid from vm_map and pmap interface

- launch
This is a cosmetic change for the `launch` script. Specifying a debugger by using `-D` flag implies debug mode enabled with `-d`, so one can skip `-d` when using non-default debugger.
> ./launch script: -D flag implies -d

- Makefile.common
- user/Makefile
This branch improves `make` output, so that processed files are represented by their path, not just their name. Current output is confusing for files from different directories that share identical names.
Old output format (fragments):
```
[CC] thread.c -> thread.o
[CC] pcpu.c -> pcpu.o
[AS] start.S -> start.o
[LD] prog.o -> prog.uelf
[CC] thread.c -> thread.ko
```
New output format:
```
[CC] sys/thread.c -> sys/thread.o
[CC] sys/pcpu.c -> sys/pcpu.o
[AS] user/start.S -> user/start.o
[LD] user/prog.o -> user/prog.uelf
[CC] thread.c -> thread.ko
```
This works even for multi-level recursive Makefiles. It also works when `make` is called in a subdirectory.
> Track file directory in make output

- sys/sched.c
Shouldn't this be "==" instead of "&" ?
By the way, since me and @rafalcieslak managed to find some bugs in @cahirwpz implementation, wouldn't it be good idea to make pull requests so everyone can do code review?
> Serious typeo in sched_switch code (& and ==)

- sys/runq.c
No need to explain what's going on here. This causes bus error if runq is empty (which happened in my case).
> Unsigned variable is always bigger than zero!

- sys/exec.c
- user/Makefile
These proposed changes simplify adding multiple user programs to `./user`, by implementing a generic `Makefile` and templates for selecting embedded elf image in `get_elf_image`.
> Templates for get_elf_image and generic ./user Makefile

- include/vm_map.h
- sys/vm_map.c
- vm_map.c
This branch introduces `vm_map_findspace`, which finds a free space in virtual memory large enough to fit requested length. It is roughly based on FreeBSD's `vm_map_findspace`. This branch also includes some formatting fixes unrelated to `findspace`, because *one of us* is not running `make format` before each commit. I've also included a pretty compelling test case which should be enough for now.
I need this function to correctly implement anonymous mappings for `mmap` syscall. And I need that syscall in order to implement `fork`, because our current "no-processes" thread model requires me to actually implement `clone`, with adjustable level of memory sharing - and traditionally it is the caller to clone who has to provide a new stack for child thread, so it will need `mmap` to create …
> Implemented vm_map_findspace

- include/mutex.h
- sys/malloc.c
With upcoming turnstiles I find old mtx_t unnecessary. We should follow FreeBSD convention and make mtx_t good, old blocking mutex.
> Remove mtx_t

- Makefile
By default, the new toolchain builder downloads all sources to `./toolchain/mips/.build/src`. We don't want to pull tags from these sources, not only they are irrelevant, but it also takes a very long time to `make tags`.
> Exclude toolchain path from tags file search

- Makefile
- include/mips/cpu.h
- include/mips/m32c0.h
- include/mips/m32tlb.h
- include/mips/mips32.h
- include/mips/notlb.h
- include/mips/regdef.h
In order to become independent from ImgTech's toolchain, this branch imports the mips-specific header files (and their recursive dependencies) we use. I've run `clang-format` on these, except for `m32c0.h` which becomes corrupt in the process. This branch also edits `make tags` rules so that tags are no longer imported from toolchain headers, it also corrects `make format` rule so that `clang-format` no longer tries to process toolchain source files.
This branch fixes #115.
Note that `P` in `Makefile.common` is unmodified. Enabling new toolchain emits a ton of new warnings (as we are migrating gcc 4.8 -> 5.2), so these need cleaning up before compilation succeeds, and these deserve a separate PR (though temporarily disabling -Werror got me a correctly working kernel image!).
> Import ImgTech MIPS headers

- Makefile
- Makefile.common
- include/common.h
- launch
- mips/pmap.c
- sys/callout.c
- sys/exec.c
This tiny change to `Makefile.common` enables the custom toolchain - **if available** at host. Since this would be a major breaking change for other contributors (and for travis), for some transitional period both toolchains are supported. Make simply checks whether `mipsel-unknown-elf-gcc` is available, and if not, it falls back to `mips-mti-elf-*`. In both cases compilation succeeds, and the produced kernel image operates normally.
Also I had to disable `-Wformat`. gcc 5.2 is very confused about one particular detail that appears in numerous places in our sources, namely printing a `vm_addr_t` (or similar address types) with a `%lx`. `vm_addr_t` is AKA `unsigned int`, so gcc complains that we should not use the `l` prefix for printing. I might go ahead and correct all `%lx` to `%x`, but …
> New toolchain support in make rules

- include/atomic.h
- mips/Makefile
- mips/atomic.c
This PR adds atomic operations stolen from FreeBSD. They are used to implement mutexes on other branch, thus tested and proved to be working.
> Basic atomic operations (compare and swap, atomic store)

- include/thread.h
- include/turnstile.h
- sys/Makefile
- sys/turnstile.c
Add basic turnstile data structure. I decided to implement all I need to get the blocking mutexes done. And it turns out I needed only turnstile_wait and turnstile_signal. I'm still unsure about it working but I spent some time on testing implementation of turnstile using mutexes on other branch and everything seems to be ok. I'd like this and mutexes to be merged ASAP, so I can spill mutexes around the code and we can start testing if this implementation is correct. In other branch I plan to add some debugging commands to make life for potential debugging person easier.
This is very tiny, but it's all that is necessary to implement blocking mutexes. Since we don't really have high-level scheduler which reassigns priorities, we don't really have priorities and we don't need to solve …
> Add turnstile data structure

- include/vm_map.h
- sys/vm_map.c
Extracted from #112 per [request](https://github.com/cahirwpz/mimiker/pull/112#issuecomment-258784549). `vm_map_findspace` would sometimes return an address lower than `start`, this patch fixes it to never consider spaces that would begin before `start`.
> Fix for vm_map_findspace start strictness

- user/Makefile
- user/mimiker.ld
- user/prog.c
- user/start.S
This branch enables small-data section and prepares `$gp` for usermode programs. Some details are explained in the discussion [here](https://github.com/cahirwpz/mimiker/pull/107#issuecomment-259316612). The updated test `prog.c` verifies that data can be successfully accessed with the `gp`.
I mentioned that while testing this I encountered a serious bug with context saving; I did not - it was my test that was incorrect.
> Enabled _gp support for usermode programs

- .travis.yml
- launch
- rtc.test
QEMU works most of the time. In `rtc.elf`even first printed time is correct(OVPsim).
But sometimes (30% of runs) mimiker stops/crashes before main. Even errors are non-deterministic.
Last printfed message is `[startup] subsystems initialized` or `[thread] Activating 'main' {0x802be030} thread!`. When run with debugger attached it stops just after `kmalloc_init(td_pool)` in `thread_init`.
QEMU likes to exit with different messages: one of them is
`dma: command fc not supported`
`dma: command ff not supported`
`qemu: unsupported keyboard cmd=0x78`
`qemu: unsupported keyboard cmd=0x14`
`qemu: unsupported keyboard cmd=0x10`
`qemu: unsupported keyboard cmd=0x80`
and another one
`PFLASH: Possible BUG - Write block confirm`.
When started with debugger only second one appears.
I'm not sure if we …
> Added qemu support to lauch script

- user/Makefile
- user/prog.c
- user/syscalls.c
Thanks to crosstool-ng already building newlib for us, it turned out that enabling libc is as simple as adding `-lc` to linker flags - so this branch has a working libc demo.
Note that disabling `-nostdlib` is not the same as adding `-ld`. In particular, `-nostdlib` pulls `crti.o` and `crtbegin.o` from compiler's resources, and we are definitely not at the point where we might use them instead of our own `start.S`.
I'll continue working on this branch to add system call wrappers stubs. Kernel-side system call support will be done in a separate branch.
> Enabled libc for user programs

- Makefile
- exec_syscall.c
- include/sysent.h
- mips/intr.c
- sys/Makefile
- sys/exec.c
- sys/sysent.c
- user/Makefile
- user/syscall_test.c
- user/syscalls.c
This is an improved variant of #107. Introduces a minimal syscall vector, and implements `sys_write` stub, which may be used by user programs for writing to temporary stdout/stderr dummies.
> Syscalls vector and sys_write stub

- Makefile
- sys/Makefile
I don't like the fact that while rebasing or merging a branch which adds new files to repo I often have to resolve conflicts in makefiles, splitting this into rows should avoid these conflicts in most of cases.
> Split makefile sources into rows

- Makefile
I finally got down to cleaning up the main Makefile. My changes include:
- Correcting dependencies so that they point to files and not their parent directories
- Simplifying frequently edited variables
- Automatically generating as much as possible to reduce human-error risk (for example, creating a new test `*.c` required adding the file in two places in `Makefile`, and as some tests were present in only one of these places, the success of build varied with the order of dependency evaluation...)
- Providing slightly more documentation, as makefiles tend to get difficult to read. Minor formatting fixes.
As a pleasant effects of these changes:
- `make` no longer pointlessly rebuilds kernel `.elf`s and some other files when nothing was changed
- Fixed dependencies finally allow for …
> Major makefile cleanup

- user/syscalls.S
The last two instructions of `set_errno`, called in userspace when syscalls return error code:
```
jr      $ra
addiu   $sp, $sp, 24
```
are compiled into:
```
jr      $ra
nop
addiu   $sp, $sp, 24
```
so the procedure does not restore `$sp` correctly! This branch fixes this issue by adding `.set noreorder` assembler directive, which makes it trust us about branch delay slots.
I hope we can merge this ASAP, because this is blocking all my other syscall-related work. Also: let this be a reminder to us all to always run tests even after cosmetic changes!
> High-priority fix for syscalls destroying user stack

- mips/intr.c
- sys/sysent.c
Merely a minor cosmetic change to cleanup kernel debug messages for syscalls to make debugging syscalls easier, at least until we can properly filter messages.
> Unified syscall debug output

- exec.c
- include/context.h
- include/thread.h
- mips/context.c
- mutex.c
- sched.c
- sys/thread.c
- thread.c
Basically this modifies
```
thread_t *thread_create(const char *name, void (*fn)());
```
into
```
thread_t *thread_create(const char *name, void (*fn)(void *), void *arg);
```
so that one can optionally pass an argument to the thread function, in a manner similar to `pthread_create`. This mechanism is necessary to create an `init` kernel thread, as it needs to start arbitrarily many threads.  Incidentally this also cleans up thread creation in `sched.c`.
> Implemented argument passing when creating a new thread

- Makefile
- exec_fd_test.c
- sys/exec.c
- user/Makefile
- user/fd_test.c
Simple user program testing various descriptor features, extracted from #152. Naturally, as for now these tests do not work at all, but - at the point of writing this - #152 passes these tests successfully, so they are *probably* correct. Luckily the tests are now much easier to read, as I've introduced some convenient macros.
> File descriptors test

- user/Makefile
- user/mimiker.ld
When I was repairing the linker script for user programs so that they could use `gp` correctly, I forgot to add the `.sbss` section. It is definitely needed to compile some external programs. I've consulted the gcc's default linker script for our platform, so the section layout should be correct.
I've also asked `user/Makefile` to NOT remove `start.o` when other targets are complete, so that I can use `start.o` when linking external programs.
> Fixed .sbss section for user programs

- mips/exc.S
Some recent changes made us never actually enter user mode, and completely invalidate `C0_STATUS` when we leave it.
> Minor fix to how C0_STATUS is handled when transitioning from/to user mode

- user/mimiker.ld
For some reason the tests I originally used happened to have a page-alligned end of `.sdata` section, but that's not always the case, and our `exec` implementation requires the subsequent segment `.sbss` to be page-alligned.
> Fixed .sbss allignment

- Makefile.common
We lost this dependency at some point. Without it everything builds just fine, but touching a file in, say, `./sys` did not cause the tests to rebuild.
> Fixed missing rependency *.elf: KRT

- sys/Makefile
- sys/dev_uart.c
- tests/vfs.c
Here's a quick implementation of a `/dev/uart` device. We need it because #152 makes user programs unable to output any text - and using a `/dev/uart` for fds 1 and 2 will be a good workaround (until we have terminal support...).
I did not implement reading from UART, because it is not as crucial at the moment, and we need to discuss `poll` behavior beforehand.
Also (*especially for those, who did not follow VFS development*), this PR demonstrates how simple it is to implement new devices using the interface we have. Of particular note is `SET_ENTRY` at the end of `dev_uart.c` which uses linker set to have `init_dev_uart` called when `devfs` starts, without modifying `devfs` sources.
> Basic /dev/uart stub

- include/devfs.h
- include/mount.h
- sys/devfs.c
- sys/startup.c
- sys/vfs.c
This branch introduces a linker set which gathers all filesystem types implemented in the kernel. It also uses `vfs_init` the way it was intended to be used.
Naturally, this is useful for implementing new file systems, if anybody, hypothetically, would like to do that.
> Filesystem type registration with a linker set

- Makefile
- Makefile.common
- include/exec.h
- include/ktest.h
- include/test.h
- launch
- mips/malta.c
- sys/Makefile
- sys/main.c
- tests/Makefile
- tests/callout.c
- tests/crash.c
- tests/exec.c
- tests/exec_fd_test.c
- tests/exec_misbehave.c
- tests/linker_set.c
- tests/malloc.c
- tests/mutex.c
- tests/physmem.c
- tests/pmap.c
- tests/producer_consumer.c
- tests/rtc.c
- tests/sched.c
- tests/strtol.c
- tests/syscall.c
- tests/thread.c
- tests/uiomove.c
- tests/vfs.c
- tests/vm_map.c
This branch cleans up the build process by reducing the final output to just a single `.elf` kernel image. The kernel now accepts `init=PROGRAM` and `test=TEST` arguments, which may be used to run a user-space program as the init process, or run the specified kernel test. This slightly generalizes our test architecture, and improves build time.
Tests are now declared with `TEST_ADD(name, function_implementing_test)`, which appends appropriate data to a linker set. Tests no longer provide their own version of `main`, the only `main` is now implemented in `sys/main.c`. Kernel image is linked once, to `mimiker.elf` in the root directory. The launch script uses `mimiker.elf` by default, so it may be used like this:
```
./launch init=fd_test
```
or
```
./launch -td test=vm_map
```
As always, …
> Implemented init= and test= kernel arguments support

- include/mount.h
- include/mutex.h
- sys/devfs.c
- sys/file.c
- sys/filedesc.c
- sys/mutex.c
- sys/vfs.c
- sys/vfs_syscalls.c
- sys/vnode.c
- tests/mutex.c
- tests/producer_consumer.c
@rafalcieslak, @coodie Please review.
I've noticed some locking patterns while reviewing #167 that made me wondering if it's right time to add recursive mutexes. This is my first attempt. I've completely got rid of `atomic_cmp_exchange ` as we run whole OS on single core - critical section will do for now.
> Simplify mutex implementation, add recursive capability.

- Makefile.common
- include/common.h
- include/elf/elf_generic.h
- include/linker_set.h
- include/mips/cpu.h
- mips/malta.c
- mips/stack.c
- stdc/include/low/_stdio.h
- stdc/kprintf.c
- stdc/snprintf.c
- stdc/stdlib/qsort.c
- stdc/string/bzero.c
- stdc/string/memchr.c
- stdc/string/memcpy.c
- stdc/string/memset.c
- stdc/string/strcmp.c
- stdc/string/strcspn.c
- stdc/string/strlcat.c
- stdc/string/strlcpy.c
- stdc/string/strlen.c
- stdc/string/strncmp.c
- stdc/string/strsep.c
- stdc/string/strspn.c
- stdc/wctomb.c
- sys/exec.c
- sys/vfs.c
As requested, this branch gets the kernel to compile in a fully free-standing environment. This is achieved with a combination of `-ffreestanding` and `-nostdinc` flags. However, as `-nostdinc` disables too much, the build script will query `gcc` about it's install dir, and will manually add include directories where compiler headers (not standard library headers) are located.
I've had to include some extra type definitions to `common.h`. It also turned out that the main user of standard library headers is `_stdio.h`, and it pulls ~20 headers as dependencies; so I've stripped it down from various functions we don't use anyway, so that it no longer requires that many type definitions.
> Disabled std library headers use in kernel

- .clang-format
- include/common.h
- include/file.h
- include/vfs_syscalls.h
- include/vnode.h
- sys/file.c
- sys/sysent.c
- sys/vfs_syscalls.c
- sys/vnode.c
Cherry-picked from the [`doom_test3`](https://github.com/rafalcieslak/mimiker/tree/doom_test3) branch, slightly updated to reflect recent changes (error return value sign, some renamed functions).
As usual, some files I edited weren't formatted correctly.
Note that as for now no filesystems support `VOP_GETATTR`, but `cpio` eventually will.
> Basic lseek and fstat interface

- sys/startup.c
I've noticed that when kernel tests are running, the scheduler was not started (`sched_active` is `false`). This makes it impossible to use conditional variables in tests, and these would be very useful for verifying multi-threaded tests.
Apparently the `sched_run()` that appears in `kernel_init` was never called, because it was preceded by a `thread_switch_to`. I've fixed this so that the `"main"` thread is properly registered in the scheduler, and then `sched_run()` is called.
> Fixed scheduler never getting started

- sys/vfs.c
- sys/vnode.c
- tests/vfs.c
This is a fairly simple fix for vnode ref counts that I've discovered while working on #200.
> Fixed vnode ref counting on vfs_open and vnode_generic_close

- tests/pmap.c
This is a straight-forward fix for an obvious bug in `pmap_kernel` test, which I've found while working on #202.
> Fixed kernel_pmap test destroying kernel pmap

- include/callout.h
- sys/callout.c
- sys/startup.c
- tests/callout.c
~~**NOTE: This branch incorporates #197, because it uses conditional variables, and these need a working scheduler!**~~
I've looked at our existing `callout` test, and it's absolute trash. It needlessly messes up internal state, and only works if we're lucky enough to have no clock interrupts appear both in the meantime and before the test.
Here are three safer tests that verify whether callouts are processed correctly, whether the order of execution is right, and whether removing callouts actually stops them from being executed. They use conditional variables to notify the main test thread from a callout-triggered function about state change.
> Replaced callout tests

- .travis.yml
- toolchain/README.md
- toolchain/deb/README.md
- toolchain/deb/install
Toolchain is installed in /opt. `$PATH` isn't touched, so `.travis.yml` exports new value.
`dh_make` is required to package.
> Toolchain in deb package

- run_tests.py
- sys/ktest.c
Some cosmetic fixes to test output display. Most importantly, I've learned about `pexpect`'s `before` which allows me to gather and print out the entire kernel output in case of a failed test - this will make it much easier to investigate travis failures.
> Minor improvements to ktests output

- sys/malloc.c
The dash in:
```
"[kmalloc]  malloc_arena %p – %p:\n"
```
was a non-ascii character. This disables travis from correctly displaying failed test output!
It looks as if someone's editor used automatic fancy unicode character substitution.
> Removed a non-ascii character from kmalloc_dump

- include/ktest.h
- sys/ktest.c
- tests/malloc.c
Yet another ktest feature: Tests added with `KTEST_ADD_RANDINT` will be passed a random (deterministic) integer as an argument. The range [0..max] may be specified as an extra argument when registering the test.
> Implemented ktests with a random integer

- .gdbinit
- include/common.h
- include/ktest.h
- sys/Makefile
- sys/assert.c
- tests/Makefile
- tests/broken.c
- tests/callout.c
- tests/malloc.c
- tests/physmem.c
- tests/pmap.c
- tests/thread.c
- tests/uiomove.c
- tests/vfs.c
- tests/vm_map.c
I've recently noticed @czapiga using `assert` when writing new tests, while he should choose `ktest_assert` instead, as this variant correctly notifies the testing framework about a failure.
We can avoid this inconvenience by defining `assert` to be an alias of `ktest_assert` when compiling sources in `./tests` directory.
> Convenient ktest_assert alias

- launch
This bug was originally discovered by @strzkrzysiek.
When launching the kernel using `./launch` script with `-t` option (which is useful for redirecting kernel output to another terminal or file) and `-d` option simultaneously, both qemu monitor and gdb interface will hook to the same terminal, and will share input/output, making it impossible to enter gdb commands.
This patch disables the qemu monitor in test mode - we do not use the monitor interface anyway.
> Fixed test/server inconsiscency in launch script

- tests/callout.c
When fixing callout implementation I forgot to increase time intervals for `callout_stop` test. 40ms is twice as much as the largest qemu lag on travis I've ever experienced, so it should be just enough for now.
> Increased time intervals for callout_stop test

- launch
- run_tests.py
This is a particularly nifty feature: When test results are inconclusive because neither success nor failure were reported within timeout, the `run_tests.py` script will launch `gdb` to get some information (`info registers`, `backtrace`, `kdump threads`, etc.) about kernel state, which may give some hints on why did it hang.
> Automatically inspect kernel state on test deadlock

- sys/sched.c
The idle thread would always stay marked as `TDS_RUNNING`, this patch fixes this problem.
> Fixed idle thread always marked as running

- include/common.h
- include/thread.h
- mips/pmap.c
- sys/sysent.c
Uhm, this is what happens when I move features between multiple branches too much. Funny that the compiler did not consider this as an error.
> Fixed thread_exit interface

- tests/malloc.c
`malloc_randint` fails occasionally, when the generated random integer - used as the size of allocation - is close to the size of entire pool, because malloc is unable to fit the `mem_block_t` structure.
At b3925e8bcde231643ccb4320c8f6001884bf2025, an example offending seed is (for OVPsim):
`test=all seed=516288384 repeat=5`:
```
Running test malloc_randint.
[pmem] pm_alloc {paddr:3c0000 size:64}
[malloc.c:196] memory exhausted in 'testing memory pool'
```
This branch fixes the problem by slightly reducing the range of random integers for this test.
> Reduced randint range for test_malloc_random

- sys/mutex.c
- sys/rwlock.c
- sys/sched.c
I find it annoying to see:
```
[sleepq.c:68] Sleep 'main' thread on '(null)' (0x801b8704)
```
while we have an interface for specifying names for wait channels. This branch improves some calls to `sleepq_wait` so that they provide meaningful name, instead of lazily passing a `NULL`.
I've also decided to rename the thread which enters `sched_run` to `idle thread`, otherwise we end up with both `kernel-main` and `main` in output logs, and one has to KNOW that `kernel-main` had become the idle thread and now functions as one.
> Improved debug log on deadlocks

- mips/context.c
This is a tiny change, but it fixes a huge bug.
To understand it, please have a look at the ending of `kern_exc_leave`:
```
LOAD_REG($k1, SR, $sp)
mtc0    $k1, C0_STATUS
move    $sp, $k0
sync
eret
```
If the assumption mentioned in comment is not met, that is: EXL bit of the status register stored in saved context is **not set**, then between the `mtc0` instruction and `eret` an interrupt may arrive. This is unacceptable, because it would overwrite the just-restored context (in particular, it overwrites EPC address with the address of the `move` instruction, resulting in a endless loop over the last three instructions). That seems unlikely to happen, so here's a proof:
b3925e8bcde231643ccb4320c8f6001884bf2025, OVPsimp: `test=all seed=823261445 repeat=5`
EDIT: You can also see the problem …
> Fixed exception level for new threads

- include/thread.h
- sys/thread.c
During `thread_exit`, the mutex on `zombie_threads` must be unlocked before critical section is left. Otherwise we risk preemption before the mutex is unlocked, and as the thread is TDS_INACTIVE, it will never resume execution - permanently blocking any other threads from locking on the mutex.
I've observed this problem several times on my local machine, but I've only managed to trigger it with QEMU, and thus I cannot provide a seed for reproducing the issue.
> Fix deadlock on zombie_threads_mtx

- tests/callout.c
This branch **does not** address issues of #213! It barely fixes the callouts tests so that they won't fail when they should not. This is done in three steps:
- Wrapping callout setup and sleepq wait in a critical section. This prevents sleepq from being signalled before we get to wait on it (`sleepq_wait` takes a long time to print a debug message, so - until #239 is ready - there is some chance of preemption: [see this Travis log](https://travis-ci.org/cahirwpz/mimiker/builds/219684633)).
- Ignoring callout execution order, since we no longer care about it.
- Reducing time values. Using critical sections and ignoring order allows for tighter timing, which in turn makes the tests execute significantly faster, which is particularly observable when testing with `repeat=5`.
> Minor fixes to callout tests

- sys/dev_uart.c
- user/prog/prog.c
This is just filling in the missing glue between `uart_cbus` and `dev_uart`, so that user programs can get some bytes from uart input. 
A proper solution will require device infrastructure and terminal support - but we're far away from that.
> Implemented dev_uart_read

- sys/exec.c
We've discussed this some long time ago, and I though I've already fixed this - but apparently not. Our user program stack is far too small and does not grow. This tiny patch increases stack size to 8MiB, which should be enough for most programs. Since the underlying pages are provided on-demand, this change has no performance penalties.
> Increased stack size to 8 MiB

- include/common.h
- include/vnode.h
- sys/initrd.c
We've recently defined our `dev_t`, `ino_t`, `mode_t` (probably when the cpio ramdisk was introduced). Since then our `struct vattr` is no longer binary compatible with newlib's `struct stat`. This results in user programs being unable to correctly ask about file size etc! This branch fixes our vattr structure definition (in newlib compatibility mode) so that it matches newlib's layout.
I guess we'll have to eventually look into porting newlib, but until then this will be enough to get some userspace programs running correctly.
> Fixed file attr structure's newlib compatibility

- sys/sched.c
A closer investigation uncovered that `sched_switch` is flawed and it's critical section ended too soon. Before `ctx_switch` re-disables interrupts, they are enabled for a short while by `critical_leave()`. If the thread gets preempted at that very moment, we end up with multiple threads marked as `RUNNING`, neither are added to run queue, etc. which caused the deadlock we occasionally observed in Travis results.
This fix extends the critical section until after `ctx_switch`, which prevents the described problem. I've restarted the Travis test 10+ times without a single failure.
I expect this is the last change needed to fix Travis false negatives.
> Fixed occasional deadlock on `thread_join`

- include/uio.h
- sys/initrd.c
- sys/uio.c
- sys/vfs_syscalls.c
- sys/vnode.c
- tests/uiomove.c
- user/fd_test/fd_test.c
While I've been working on getdirents syscall I had 'elegancy problem'. My implementation of getdirents system call was incredibly ugly and I couldn't really come up with elegant way of fixing it.
I have looked into NetBSD code and noticed that it is indeed fault of our implementation of 'uiomove'. In our case `uio_offset` is IN argument of uio, while in fact this argument is 'OUT' argument supposed to show how much of the entire UIO operation was shifted. This argument is also used in setting proper file reading offsets. I can explain it in more details on seminary. Here is link to the NetBSD's implementaiton of uiomove:
http://bxr.su/NetBSD/sys/kern/subr_copy.c#99
Here is example usage in tmpfs in getdirents operation:
http://bxr.su/NetBSD/sys/fs/tmpfs/tmpfs_subr.c#807
Note how they …
> Uiomove offset

- include/pci.h
- mips/pci.c
It took me several weeks to fully debug my VGA driver on QEMU - which made me quite knowledgeable about vga, pci and memory management implementation in QEMU (phew!). My final conclusion is that the BARs on QEMU PCI are uninitialized, and therefore QEMU fails to create memory mapping when we request to enable memory access to a PCI device.
On OVPsim, BARs are (presumably) configured by bootloader/BIOS. We compute the addresses we're going to use in `pci_bus_assign_space`, and it happens that OVPsim's choice matches ours. This is not the case for QEMU, where these registers are uninitialized and contain junk values - which I do have confirmed with QEMU's sources and by tracing a lifetime of a PCI device in QEMU with a debugger, in multiple QEMU versions (2.0, 2.5, 2.8.1).
So if these …
> Inform the PCI bus about our space assignment

- Makefile.common
- include/console.h
- include/mips/uart_cbus.h
- include/stdc.h
- mips/malta.c
- mips/uart_cbus.c
- stdc/kprintf.c
- sys/Makefile
- sys/console.c
- sys/dev_cons.c
- sys/exec.c
- tests/vfs.c
The change aims at decoupling CBUS UART driver code from console-like device functionality. The interface is loosely based on *BSD console device interface present in [cons.h](http://bxr.su/NetBSD/sys/dev/cons.h) and described in [cons(9)](http://netbsd.gw.com/cgi-bin/man-cgi?cons+9+NetBSD-current).
To make linker sets work for files in `mips` subdirectory I had to modify top-level `Makefile` (that took me some time to figure out).
In long run I'm aiming at decoupling driver code from hardware resource with help of [bus_space(9)](http://netbsd.gw.com/cgi-bin/man-cgi?bus_space+9+NetBSD-current)-like interface which has been partially implemented in [bus-space](https://github.com/cahirwpz/mimiker/compare/bus-space) branch.
> Decouple console functionality from UART driver code

- include/bus.h
- include/common.h
- include/ns16550.h
- mips/Makefile
- mips/cbus.c
- mips/uart_cbus.c
Main purpose of this PR is to show how `bus_space` and `resource` structures help to decouple driver code from actual hardware resource(s) (in this case 16550 UART register set). Same code should be capable of handling `tty0` and `tty1` by just replacing `cbus_uart` in `in` and `out` functions to resources describing UART devices in *FDC37M81x* controller attached to ISA bus in *PIIX4* chipset.
Next step is to perform similar task (i.e. decoupling) for *GT-64120* PCI-bridge chipset by introducing `pci_read_config` and `pci_write_config` functions and corresponding function table.
> Decouple ns16550 driver code from hw resource access method

- include/stdc.h
- stdc/Makefile
- stdc/sscanf.c
- stdc/stdio/__scanf_core_int.c
Simple as that. I need `sscanf` for another branch I'm working on, and I know you like to import new stdc functions in separate pull requests. The implementation I picked from `smallclib` is the natural counterpart of `snprintf` we already use. I've only modified `include` directives to match our header file layout.
> Imported sscanf

- include/uio.h
- sys/exec.c
- sys/vfs_syscalls.c
- tests/initrd.c
- tests/vfs.c
This is alternative solution to PR #274. I think I've found the cleanest solution to the problem, that does not require using rare C extensions.
> Initializer macro for single UIO transfer

- include/mutex.h
- include/proc.h
- include/thread.h
- sys/Makefile
- sys/exec.c
- sys/fork.c
- sys/proc.c
- sys/startup.c
- sys/sysent.c
- user/test_fork/test_fork.c
This branch introduces `proc` structure. In order to keep this change minimal, I've not removed any fields from `thread` structure, and `proc` is not very useful at the moment. I suggest introducing more fields to `proc` in subsequent PRs.
I've modified `fork` so that it creates a new process for the new thread, and `exec` so that it creates new process for current thread (if called by a kernel thread). I've also implemented `getpid` syscall and `proc_get_by_pid` convenience function.
This should be enough to push #271 (Basic signal support) forward.
> Process structure stub

- sys/vfs_syscalls.c
Fixed a tiny bug in `do_lseek`, where the file requested with a descriptor was assumed to be readable. This is not the case e.g. for `/dev/vga/fb`, and thus user programs were unable to seek back to framebuffer start.
> Fixed seeking for write-only files

- include/proc.h
- include/thread.h
- sys/exec.c
- sys/fork.c
- sys/thread.c
- sys/vfs_syscalls.c
This was certainly simpler than `uspace`. Note that until we fix `exit` to kill all process' threads, the file descriptor table never gets released (because processes are never destroyed).
> Moved fdtable from thread_t to proc_t

- include/device.h
- include/malloc.h
- sys/Makefile
- sys/device.c
- sys/drv_stdvga.c
I've removed `M_STDVGA` memory pool and created a generic `M_DEV`. I also took the opportunity to rename `stdvga.c` to `drv_stdvga.c`.
By the way, could we please merge [`device`](https://github.com/cahirwpz/mimiker/tree/device) branch ASAP and fix it later? Pretty much everything I'm trying to experiment with requires these `device` and `driver` structures to be present.
> M_DEV memory pool

- include/malloc.h
- include/mount.h
- include/sysent.h
- include/vfs_syscalls.h
- sys/devfs.c
- sys/initrd.c
- sys/malloc.c
- sys/startup.c
- sys/sysent.c
- sys/vfs.c
- sys/vfs_syscalls.c
- tests/vfs.c
Initially I only wanted to remove the `if (strncmp(path, "/dev/", 5) == 0)` and associated `vfs_root_dev_vnode`, turned out some extra cleanup to the mount process was required, and I ended up with an elegant
```c
vfs_domount_named("initrd", "/");
vfs_domount_named("devfs", "/dev");
```
in `kernel_init(...)`.
> Simplified mount interface

- include/vnode.h
- sys/vfs.c
- tests/vfs.c
In current version of vfs_lookup there was a 'bug' or more likely a misunderstanding with how lookup is supposed to work. The bug is about performing vfs_lookup where the leaf (last directory on path) has something mounted under it, in this case we want to return the mounted child.
I have looked up at FreeBSD implementation to have better understanding and possibly ease implementation, but it is incredibly difficult to read because of all the cases it covers + path caching.
Here is vfs_lookup counterpart in FreeBSD:
[http://bxr.su/FreeBSD/sys/kern/vfs_lookup.c#124](http://bxr.su/FreeBSD/sys/kern/vfs_lookup.c#124)
Note that namei procedure calls lookup in few places, while lookup performs mounting fix in this line:
[http://bxr.su/FreeBSD/sys/kern/vfs_lookup.c#789](http://bxr.su/FreeBSD/sys/ …
> Vfs lookup mount fix

- .gdbinit
- .gdbinit.template
- .gitignore
- include/common.h
- launch
- launcher/common.py
- launcher/outputs.py
- launcher/simulators.py
- mips/exc.S
- sys/assert.c
- I've added a `user_return` label user before `eret` in `user_exc_leave`. When debugging user programs and/or syscalls, it is very convenient to place a `tbreak` on this label, to continue debugging the user application from the moment the current system call returns.
- As our kernel `main` no longer does anything interesting, I've changed the implicit breakpoint from `main` to `kernel_init`, so that a default debugging session starts there.
- I've added a boring `panic_fail` function (similar to `assert_fail`) so that I could add an implicit breakpoint on it. This way a default debugging session will not only automatically stop at failed assertions, but also at any panic condition.
> Minor debugging experience improvements

- .clang-format
- include/common.h
- include/mutex.h
- include/rwlock.h
- include/sync.h
- mips/pmap.c
- mips/signal.c
- sys/condvar.c
- sys/devfs.c
- sys/exception.c
- sys/file.c
- sys/filedesc.c
- sys/klog.c
- sys/malloc.c
- sys/mmap.c
- sys/mutex.c
- sys/pool.c
- sys/proc.c
- sys/rwlock.c
- sys/sbrk.c
- sys/sched.c
- sys/signal.c
- sys/sleepq.c
- sys/sync.c
- sys/thread.c
- sys/vfs.c
- sys/vfs_vnode.c
- sys/vm_map.c
- tests/producer_consumer.c
During code reviews I have noticed that `mtx_scoped_lock` blends visually with the surrounding code too much. More important issue is that it does not force a programmer to think how long a mutex is really needed to be acquired, so the mutex may be held for code that does not require such assumption. To address the problem we could write following code with `mtx_scoped_lock`:
```c
{
mtx_scoped_lock(a_lock);
...
}
```
... or use `WITH_MTX_LOCK`:
```c
WITH_MTX_LOCK (a_lock) {
...
}
```
Please give me your feedback on usefulness of this construct.
> Python-like with statement for mutex locking

- include/interrupt.h
- include/mutex.h
- include/thread.h
- mips/malta.c
- sys/devfs.c
- sys/initrd.c
- sys/interrupt.c
- sys/proc.c
- sys/thread.c
- sys/vfs.c
I was in a mood for cleanup today. I've always wondered why:
1. We rarely use `TAILQ_HEAD_INITIALIZER` macro
2. We have not implemented a `MUTEX_INITIALIZER` macro
These are very useful for initializing static/global variables. I've applied them consistently where applicable, and that rendered as much as three `init_` functions useless (!), so I've removed them entirely.
> Simplified mutex and tailq initialization

- include/systm.h
- mips/copy.S
- mips/signal.c
- sys/sysent.c
Mixing `copy{in,out}` with `{su,fu}word32` in syscall implementations started looking awkward, as the latter did not return `EFAULT`. Frankly, I can no longer justify `{fu,su}word32` existence in our code base, so I removed it.
Instead of it I introduced generic `copy{in,out}_s`, which simplified code using regular `copy{in,out}` as well.
> Simplify copying data between user-space and kernel-space

- include/klog.h
- sys/klog.c
NOTE: I know I can set any mask I want on my own, but this is about changing the ***deafult experience***.
At this point `pmap` logs are extremely verbose, and they render the output completely unreadable and unattractive. When running `test_fork`, pmap logs take 75% of the output! Just see for yourself how much of a difference it makes: [completely useless output](https://pastebin.com/PQxCgpUY) versus [clean description of what the kernel is doing](https://pastebin.com/HQ1kGCpe). Stunning!
Furthermore, disabling `pmap` logs by default should increase the speed of automatic tests a lot.
And it's not like we need to see these messages by default, when was the last time any of us had to debug pmap behavior? We can explicitly re-enable it when working on pmap.
> Disable pmap in klog mask by default

- sys/sysent.c
This bug was introduced with #335 (Simplify copying data between user-space and kernel-space). `copyout_s` would overwrite the value returned by `do_waitpid`, which is the PID of the process we've waited for.
We don't have tests in place that would detect such issue, which is why I find #328 (Implemented utest user program) important.
> Fix waitpid return value

- include/mips/malta.h
- mips/gt64120.c
- tests/rtc.c
This change shows that interrupts are correctly routed from ISA devices to the CPU.
2Hz periodic interrupt is used to wake up main thread in order to print a message.
> RTC driver mockup

- sys/vfs_vnode.c
I suggest to revert this change which was introduced as a part of this [major patch](https://github.com/cahirwpz/mimiker/commit/0bb05a098b27936df30fbbcadc38f9387174dc49). I see no point of it, and because of this change **usermode programs are no longer able to write to stdout**. Note that:
```
O_RDONLY = 0
O_WRONLY = 1
O_RDWR = 2
```
These are numbers, not bitmasks. Thus masking mode with `O_RDWR` causes files that are requested in `O_WRONLY` mode (like stdout) to be opened in `FF_READ` mode, which is incorrect.
I also urge you, again, to **manually test some user programs**, especially during such extensive changes as the one that introduced this problem, as it would immediately detect this issue and save us both time! Although... I think I shouldn't care anymore.
> Revert a major regression in vnode_open_generic

- include/devfs.h
- include/file.h
- include/vnode.h
- sys/dev_cons.c
- sys/dev_null.c
- sys/dev_vga.c
- sys/devfs.c
- sys/drv_atkbdc.c
- sys/initrd.c
- sys/vfs.c
- sys/vfs_vnode.c
This change introduces API for registering device subtrees in device filesystem. The most apparent improvement is visible on `sys/dev_vga.c` file. Same functionality is expressed with ~20 lines less, but with addition of directory listing (tested with `/bin/ls_rec`).
Registering device files (`fb`, `palette` and `videomode`) in a subdirectory (`vga`) boils down to:
```c
devfs_makedir(NULL, "vga", &vga_root);
devfs_makedev(vga_root, "fb", &framebuffer_vnodeops, vga); /* /dev/vga/fb */
devfs_makedev(vga_root, "palette", &palette_vnodeops, vga); /* /dev/vga/palette */
devfs_makedev(vga_root, "videomode", &videomode_vnodeops, vga); /* /dev/vga/videomode */
```
> New devfs API

- .circleci/config.yml
- .circleci/image/Dockerfile
Now that we're using CircleCI, I went a step further and prepared some advanced features.
- Our config no longer uses the stock `ubuntu:16.04` image, but a custom one, build with `.circleci/image/Dockerfile` - it comes with all tools we need pre-installed. That means the build environment no longer has to `apt-get` all the stuff we need, which speeds up the build process.
- I've measured time between `git push` to receiving an email warning about incorrect source code formatting - **less than 20 seconds**, this is absolutely crazy!
- You may want to copy the docker image from my repository on dockerhub (`rafalcieslak/mimiker-build-base`) to a repository created by you, although pulling it from from mine won't cause any inconvenience until you wish to publish an updated version.
- I've …
> Even cooler CircleCI

- .circleci/config.yml
Today early morning we were accepted into private beta of CircleCI workflows feature. Today evening workflows left beta, and are now available to all CircleCI 2.0 users.
This branch is barely a cleanup for CircleCI config I promised to do, and it shouldn't change general behavior. Job triggers are removed and `workflow` block describes dependencies between jobs, also `defaults` are used to share parts of configuration between jobs.
> Circleci workflows

- user/fd_test/fd_test.c
Because we don't implement relative paths expected error wasn't name too long but ENOENT so test didn't succeed.
> Fixed small bug related to relative path

- sys/uio.c
Without this fix user program in #358 which expects `read` to return 0 at the end of file fails due to assert.
> Uiomove - fails if at the end of buffer

- run_tests.py
- sys/proc.c
* Fix proc_reap race condition on non-recursive p_lock
* do_waitpid on a child did not lock parent p_lock
> Simplify acquiring strategy for process locks

- sys/exec.c
A small fixup concerning preservation of old process memory image during execve attempt.
> Fix crash during brk segment creation on execve in forked processes

- run_tests.py
Sometimes `gdb` takes longer to startup and print diagnostic messages. With following patch we give it more time. Hopefully it will resolve an issue where debugger is killed prematurely after a failed test run.
> Increased timeouts for GDB

- build/build.prog.mk
`build/flags.user.mk` adds `--sysroot=$(SYSROOT)` to `CFLAGS`, but
SYSROOT is defined in `build/common.mk`, which is included by
`build/build.mk`. Therefore, `build/build.mk` needs to be included
before `build/flags.user.mk` in order for the flag to be properly
defined.
> Swap include order so that `SYSROOT` is defined.

- include/dev/i8253reg.h
- include/klog.h
- include/mips/timer.h
- include/time.h
- include/timer.h
- mips/malta.c
- mips/timer.c
- sys/Makefile
- sys/clock.c
- sys/drv_pit.c
- sys/klog.c
- sys/timer.c
* Add infrastructure for timers that trigger callbacks either periodically or in one-shot mode.
* Introduce bintime_t structure for high-fidelity time measurement.
* Add i8254 PIT driver.
* Use timer infrastructure to trigger system clock every 1ms.
* Repurpose MIPS CPU timer for time measurement.
> Use i8254 PIT for system clock

- sys/sched.c
In Mimiker we set `TDF_NEEDSWITCH` when thread's time slice is exhausted or when some another thread with higher priority is added to run queue.
To solve issue #241 I add code to `preempt_enable` which preempts current thread if `TDF_NEEDSWITCH` is set.
Note that `critical_exit` in FreeBSD is counterpart of our `preempt_enable`.
> `preempt_enable` should switch to another thread if indirectly requested

- include/common.h
- include/interrupt.h
- include/pool.h
- include/sched.h
- include/thread.h
- sys/sched.c
- Move `td_prio_t` definition from `include/thread.h` to `include/common.h`
- Rename `td_prio_t` to `prio_t`
- Unify `prio_t` from `include/interrupt.h` with `prio_t` from `include/common.h` (now interrupt priority is `uint8_t` instead if `int`!)
- Add `#include <common.h>` to `include/pool.h`
> Little cleanup before turnstile PR

- include/sched.h
- sys/sched.c
As for now in scheduler, we have static function to change thread's active priority. In this pull request we are adding non-static function for other parts of kernel to change thread's base priority (and adjust active accordingly, which involves turnstiles).
> Added non-static set priority function to scheduler

- mips/intr.c
Since we have that function, we should use it.
> Switched to in_kernel_mode function

- mips/intr.c
- tests/utest.c
Now in case of reserved instruction exception or coprocessor unusable exception (other than FPU coprocessor), SIGILL is sent to process, instead of panicking.
> added reserved instruction handler and updated cp unusable handler to send signals

- include/signal.h
- mips/intr.c
- tests/utest.c
- user/utest/exceptions.c
- user/utest/main.c
- user/utest/misbehave.c
- user/utest/utest.h
* refactored   `test_exc_cop_unusable()`, `test_exc_reserved_instruction()`, `test_syscall_in_bds()`
* implemented tests: floating point exception, unaligned access, ENOSYS
> Testing Floating Point, Unaligned Access exceptions and wrong syscall number behaviour.

- mips/pmap.c
`pmap_setup` had a bug which made a thread clear its own UPD when switched out at a certain point during initialization of a new pmap. It also didn't preserve the calling thread's UPD mapping, so  calling `pmap_new` had a side effect of actually **activating** the newly created pmap. This PR fixes both issues.
> pmap_setup now preserves calling thread's mapping and disables preemption.

- tests/utest.c
- user/utest/Makefile
- user/utest/fpu_ctx.c
- user/utest/main.c
- user/utest/misbehave.c
- user/utest/utest.c
- user/utest/utest.h
Tests for #409 :
* test_fpu_fcsr - checks FPU FCSR register preservation. 
* test_fpu_gpr_preservation - checks 32 FPU FPR's.
* test_fpu_cpy_ctx_on_fork - checks whether child inherited parent's FPU context.
* test_fpu_ctx_signals - checks appropiate FPU context preservation across nested signal handlers which use FPU.
First 2 tests need at least one context switch to happen. nanosleep() from #366  would shorten them significantly. 
Third test depends on a scheduler.
> Tests for preserving FPU context across processes using FPU.

- sys/ktest.c
- tests/README.md
The user can now specify multiple specific tests to be run, e.g. `test=findspace,user_pmap`.
It is now also possible to specify a repeat count for tests other than `all`, so for example `test=findspace,user_pmap repeat=2` will first run `findspace` 2 times, and then run `user_pmap` 2 times.
> Allow for multiple tests to be specified on the command line + non-default repeat for user-specified tests

- mips/ebase.S
- mips/pmap.c
- Add `pmap_pte_read` and `pmap_pte_write` which don't generate TLB misses on PT access.
- Remove code handling PT accesses from `tlb_refill`
> Add PT access procedures & simplify tlb_refill

- include/condvar.h
- include/sleepq.h
- sys/condvar.c
- sys/sleepq.c
- tests/sleepq_abort.c
- tests/sleepq_timed.c
We added interruptible and timed sleep. In this PR we expose it through a higher-level `condvar` interface.
> Map sleepq interface onto condvar interface

- include/exec.h
- include/mips/ustack.h
- mips/ustack.c
- sys/exec.c
- sys/main.c
- tests/utest.c
- user/libmimiker/start.S
- user/sandbox/main.c
User programs must accept another argument `envp`, so that `main` signature is:
```c
int main(int argc, char **argv, char **envp);
```
User programs must be able to access environment variables directly:
```c
extern char **environ;
```
...or through set of functions (should be implemented by _newlib_):
```c
char *getenv(const char *name);
int setenv(const char *name, const char *value, int overwrite);
int putenv(char *string);
int unsetenv(const char *name);
```
It's shape is defined in _"System V ABI MIPS RISC Processor Supplement, 3rd edition"_, p. 30-35.
There's a useful example up there which is _"Figure 3-29: Example Process Stack"_.
> Implementation of environment variables management.

- README.md
Version 1.2 is used in continuous integration (https://github.com/cahirwpz/mimiker/blob/master/.circleci/image/Dockerfile) and link to 1.1 results in 404
> Fix broken link to older version of MIPS toolchain

- .circleci/image/Dockerfile
- Makefile
`clang-format-6.0` instead of `clang-format`, so wrong one will rise error.
Removed making symbolic link in Dockerfile, because it is not necessay now.
> Specify clang-format version in Makefile

- sys/exec.c
- sys/proc.c
A `buffer_t` structure used by `exec_args_copyin` needs more alignment.
> Alignment correction in exeve arguments roll-in function

- .gitignore
After failing to create *.swp file, vim might create other *.swX
files which will make mess in the repository
Reference: http://vimdoc.sourceforge.net/htmldoc/recover.html#swap-file
> Include more swap file extension types in gitignore

- docker/Dockerfile.tpl
`--ingroup` option allowed only one GID (https://manpages.debian.org/jessie/adduser/adduser.8.en.html)
so user was added only to `sudo` group
Previously files inside container were created with `sudo` group.
before:
```
_  mimiker git:(master) _ id
uid=1000(mimiker) gid=27(sudo) groups=27(sudo)
```
after:
```
_  mimiker git:(master) _ id
uid=1000(mimiker) gid=1000(mimiker) groups=1000(mimiker),27(sudo)
```
> Fix group id in Dockerfile

- include/sys/errno.h
- include/sys/vnode.h
- lib/libc/sys/signal.c
* Change `ENOTSUP` from 134 (newlib) to 86 (NetBSD)
* `VOP_CALL` now returns `ENOTSUP` instead of `-ENOTSUP`
> Use proper ENOTSUP value & fix VOP_CALL

- sys/kern/vfs_readdir.c
This PR:
* changes successful return value of `readdir_generic()` from `uio->uio_offset - offset` to `0`.
Why:
* `VOP_READDIR` should return 0 or error code (https://netbsd.gw.com/cgi-bin/man-cgi?VOP_LOOKUP+9+NetBSD-6.0+i386), and our `VOP_READDIR` is implemented by calling `readdir_generic()`.
> Change VOP_READDIR so that it returns 0 on success

- sys/kern/syscalls.c
**This PR fixes `ls` application.**
* Currently `sys_getdirentires()` returns 0 on success.
* According to https://netbsd.gw.com/cgi-bin/man-cgi?getdirentries+3+NetBSD-current, the return value should be:
> If successful, the number of bytes actually transferred is returned.
> Fix return value of sys_getdirentries

- bin/utest/Makefile
- bin/utest/main.c
- bin/utest/setjmp.c
- bin/utest/sigaction.c
- bin/utest/utest.h
- sys/mips/signal.c
- sys/tests/utest.c
This PR adds two `sigaction` tests:
* `sigaction_with_setjmp()` -- which checks whether we can jump out of a signal handler using `setjmp()`/`longjmp()`,
* `sigaction_handler_returns()` -- which checks whether returning from a signal handler works,
Currently the aforementioned tests fail since `sa->sa_restorer` is always NULL when we call `sigaction`. That is also the reason why currently `/bin/ksh` keeps getting SIGSEGV.
> Add sigaction tests that i.a. check returning from signal handler

- include/mips/syscall.h
`bnez` is I-type instruction so it can't jump too far.
That caused failure in build 9010 of pull/578 (#578) on CircleCI.
Now it jumps to local label, and then `j` instruction (J-type) is used to jump further.
> jmp to __sc_error inside SYSCALL is now local

- include/sys/mimiker.h
Currently our `log2(x)` implementation works fine iff `x` is a power of 2. This PR fixes it.
You can find a simple comparison of old-`log` vs new-`log` here: https://ideone.com/BNRNFU
> Fix log2 function in mimiker.h

- Makefile
- bin/lua/Makefile
- build/build.prog.mk
Files with just debug symbols for user-space executables are now placed in `sysroot/bin` - the same path as corresponding executable. They are not packed into initrd.
It makes mapping from mimikerOS executables paths to hostOS symbol files trivial.
> Separate debug symbols in sysroot

- README.md
- build/arch.mips.mk
- build/common.mk
- build/tools.mk
- include/inttypes.h
- include/mips/m32c0.h
- include/sys/cdefs.h
- sys/mips/exc.S
- sys/mips/sigcode.S
- sys/mips/switch.S
The entire kernel can now be compiled with Clang by setting the `CLANG` make variable to 1. We still use the GNU linker to link the kernel.
In order to build the whole system with Clang, either some minor adjustments need to be made in a couple of places (due to Clang being a bit more strict with its warnings), or we can turn some warnings off. You can check out a sample warning by running `make CLANG=1` in project root.
> Successfully compile the kernel with Clang

- include/sys/vmem.h
- sys/kern/vmem.c
* Added comments in `vmem.h` and to structures in `vmem.c`
* Changed `vmem_assert_locked()` function to `VMEM_ASSERT_LOCKED()` macro
* Make use of `align()` and `is_aligned()` from `include/sys/mimiker.h`
* Change `vm_quantum_mask` field to `vm_quantum`, as the latter is used more frequently (note that `mask` = `quantum` - 1)
* Delete `vmem_align_and_fit()` call from `vmem_alloc()` (no need to align as all existing segments are already aligned to `vm_quantum`, no need to check size as it's INSTANTFIT strategy)
* Delete "`btnew_prev`" case inside `vmem_alloc()`, as it would never happen
* Check that segments' start addresses are aligned to `vm_quantum` in `vmem_check_sanity()`
* Check that segments' sizes are at least equal `vm_quantum` in `vmem_check_sanity()`
> vmem: comments & simplify vmem_alloc & little refactor

- sys/kern/vmem.c
- sys/tests/vmem.c
Currently in `vmem` we support only instant-fit allocation strategy. Why is that less than ideal? Suppose we want to allocate a new block of size `N`. Then instant-fit can fail to find free segments of size `M`, if `log2(N)` is equal to `log2(M)`.
I've changed instant-fit to best-fit, which is slower in general, but always succeeds (if there exists any block of size `M`, where `M >= N`). I've also changed our test case a little bit -- the current test would fail for instant-fit strategy.
Note: in NetBSD both strategies are implemented. If instant-fit cannot find any block, the strategy is switched to best-fit.
> vmem: change instant-fit to best-fit allocation strategy

- include/sys/vmem.h
- sys/kern/kmem.c
- sys/kern/vmem.c
- sys/tests/vmem.c
* Parameters `base` and `size` have been removed from `vmem_create()` call, so that fresh `vmem` instance has no initial span, and one must call `vmem_add()` explicitly
* Implemented `vmem_free()`
* Implemented `vmem_destroy()` with extensive sanity check -- the kernel check that the destroyed `vmem` instance is empty and its memory is not corrupted
* Updated `sys/tests/vmem.c` test, so that it uses `vmem_free()` and `vmem_destroy()`
> vmem: implement free() & destroy() calls

- include/sys/vfs.h
- sys/kern/exec.c
- sys/kern/vfs.c
- sys/kern/vfs_syscalls.c
- sys/tests/vfs.c
Renamed `vfs_lookup` to make VNR naming more consistent.
> Rename vfs_lookup to vfs_namelookup.

- .circleci/config.yml
- .circleci/docker/Dockerfile
- .circleci/docker/Makefile
The `build_clang` job is failing due to the docker container not having Clang installed. It is up to @cahirwpz to update the image used in `config.yml`.
> Add Clang build & tests to CircleCI.

- sys/kern/main.c
- sys/kern/proc.c
* Array equal to `{[0] = 1, 0}` is in fact equal to `{1}`.
* Changed a comment about PID(0) -- now it's PID(1).
> Cleanup after "Do not deliver signals to zombies"

- include/sys/vnode.h
- sys/kern/tmpfs.c
- sys/kern/vfs_syscalls.c
I have changed `VOP_REMOVE` and `VOP_RMDIR` interface to take removed v-node as argument. The point is that file system implementations should not lock/unlock v-nodes in this operations. It is related to this [comment](https://github.com/cahirwpz/mimiker/issues/369#issuecomment-306614249).
> Introduce v-node locking consistency in vop operations.

- include/sys/vfs.h
- sys/kern/vfs.c
- sys/kern/vfs_syscalls.c
- sys/kern/vfs_vnode.c
We can create new regular files using `open` syscall with `O_CREATE` flag specified. I have also handled `O_APPEND` flag. It doesn't have any effect now, but at least it doesn't return with error, as it did before.
> Add support for creating file using open syscall.

- include/sys/vnode.h
- sys/kern/tmpfs.c
- sys/kern/vfs.c
- sys/kern/vfs_syscalls.c
There was some inconsistency in calling some vfs functions. They haven taken `const char *` as argument, which resulted in unnecessary memory allocations. Now they all use `componentname` like in NetBSD.
> Consistency in using componentname in vfs.

- sys/tests/sleepq.c
In `sleepq_sync` test, there are threads calling `sleepq_wait` and callouts calling `sleepq_broadcast`. This PR changes the test so that the threads are created before the callouts are set up. This minimizes the chance of a wake-up being lost.
> Minimize the race condition in sleepq_sync test

- sys/kern/tmpfs.c
Support for `.` and `..` during path lookups in tmpfs.
> Relative paths in tmpfs

- include/sys/fcntl.h
- include/sys/filedesc.h
- sys/kern/exec.c
- sys/kern/filedesc.c
- sys/kern/pipe.c
- sys/kern/proc.c
- sys/kern/vfs_syscalls.c
- sys/tests/resizable_fdt.c
Add `O_CLOEXEC` suport.
Introduce `fdent` structure into `fdtab` that contains open file and flag for file descriptor. It's based on `fdfile` from [NetBSD](http://bxr.su/NetBSD/sys/sys/filedesc.h#106).
Add `O_CLOEXEC` support for `open`, `dup`, `dup2`, `fcntl`, `execve`.
> Add O_CLOEXEC support.

- include/sys/vnode.h
- sys/kern/devfs.c
- sys/kern/tmpfs.c
- sys/kern/vfs_readdir.c
Reproduction:
- create regular file in `/tmp`,
- list content of `/tmp/` directory.
The problem was in this function:
https://github.com/cahirwpz/mimiker/blob/ee3c796e0d9d080554303090941baa2242bdb72a/sys/kern/vfs_readdir.c#L15-L17
While listing content of the directory, some child might not have any reference and this means that there isn't any vnode attached to it. Then, this causes dereferencing NULL pointer - kernel panic.
> Kernel panic during VOP_READDIR

- sys/mips/boot.c
- sys/mips/malta.c
Macro `MIPS_KSEG0_TO_PHYS` is (wrongly) applied to `KSEG2` symbols. This is misleading, though technically correct, as the definition of `MIPS_KSEG0_TO_PHYS` and `MIPS_KSEG2_TO_PHYS` is exactly the same.
> Fix inappropriate usage of MIPS_KSEG0_TO_PHYS macro

- sys/drv/ns16550.c
Fix ioctl buffer overflow.
For `bin/ls` we call `ioctl` with command `TIOCGWINSZ` which invokes `ns16550_ioctl` where we always clear 44 bytes of memory. But buffer length returned by `IOCPARM_LEN` in `sys_ioctl` is 8 so we have overflow.
After the change we clean exactly as many bytes as we have allocated.
> Fix ioctl buffer overflow.

- README.md
`README.md` was moved from `tests/` to `sys/tests/`.
> Fix link to tests/README.md

- sys/kern/thread.c
Currently inside `thread_reap` we have a `TAILQ_FOREACH` loop which basically translates to:
```
for (... ; ... ; td = td->td_zombieq.tqe_next) {
thread_delete(td);
}
```
The access to `td->td_zombieq` after calling `thread_delete` is obviously a use-after-free.
The bug has been found by KASAN:
```
======================================
ERROR: KernelAddressSanitizer:
invalid access to addr 0xc000b640
READ of size 4
code 0xfc
======================================
```
```
Breakpoint 3, panic_fail () at /home/jpszczolowski/mimiker/sys/kern/assert.c:6
6       __noreturn void panic_fail(void) {
(gdb) bt
#0  panic_fail () at /home/jpszczolowski/mimiker/sys/kern/assert.c:6
#1  0xc0132520 in kasan_shadow_check (read=0x1, size=0x4, addr=0xc000b640) at …
```
> Fix use-after-free bug inside thread_reap

- include/sys/param.h
- include/sys/proc.h
- include/sys/stat.h
- sys/kern/exec.c
- sys/kern/fork.c
- sys/kern/syscalls.c
- sys/kern/vfs_syscalls.c
Implemented [umask](https://netbsd.gw.com/cgi-bin/man-cgi?umask+2+NetBSD-current) system call. Access permissions taken as argument by `mkdir(2)` and `open(2)` system calls are now restricted by the `umask`.
> umask syscall

- sys/drv/ns16550.c
devfs is missing most of the VOP_* operations and it can cause some errors e.g. when running `stat` without arguments. It seems that implementing these operations will require quite a lot of work. 
This PR introduces simple implementation of `VOP_GETATTR` for ns16550 device.
> Add VOP_GETATTR operation for ns16550 device

- .tmux.conf
- launch
This seems to be the simplest solution. There is an env var `MIMIKER_REPO` set by `./launch`.
It is set to `./launch`'s cwd, and then it is used in `.tmux.conf` to source `/.tmux.conf.local`.
> Fix tmux overrides.

- lib/libc/sys/open.c
There was a problem with passing arguments that are variable. Now it should be OK.
> Fix arguments passing to open system call wrapper

- sys/mips/ebase.S
Previous change to `ebase.S` file caused the FPU context to be restored improperly. This is how it should be done:
* FPU has to be enabled before calling `LOAD_FPU_CTX()`,
* we should decide whether or not to restore FPU context based on `status` (not `pc`) register.
> Properly restore FPU context

- include/sys/sched.h
- sys/kern/sched.c
- sys/kern/syscalls.c
For some reason I thought that we didn't have a yield function in the kernel. Turns out we did.
> Remove yield(), use thread_yield() instead.

- sys/kern/mutex.c
- sys/kern/spinlock.c
Right now `spin_init` does not set spinlock's type to `LK_SPIN`, but it should. Look at `SPIN_INITIALIZER` implementation:
https://github.com/cahirwpz/mimiker/blob/019d2787d696c24e1d6e14b579cd5eaeedbbd92f/include/sys/spinlock.h#L33-L36
`spin_init` is used in `atkbdc` and `ns16550`:
https://github.com/cahirwpz/mimiker/blob/019d2787d696c24e1d6e14b579cd5eaeedbbd92f/sys/drv/ns16550.c#L163
So in fact `ns16550->lock` (of type `spin_t`) is used inside `cv_wait` **as a mutex**.
https://github.com/cahirwpz/mimiker/blob/019d2787d696c24e1d6e14b579cd5eaeedbbd92f/sys/drv/ns16550.c#L56-L60
But **we mustn't use mutexes in the lower half**!
> mtx_init & spin_init should set proper lock type

- sys/kern/signal.c
- sys/kern/syscalls.c
The user might want to only read a signal's disposition, in which case the input sigaction pointer will be `NULL`.
This is not an error, and we shouldn't try to `copyin` the sigaction in that case.
> Don't copyin user sigaction if the pointer is NULL.

- include/sys/condvar.h
- include/sys/lock.h
- include/sys/mutex.h
- include/sys/spinlock.h
- sys/kern/condvar.c
- sys/kern/interrupt.c
- sys/kern/klog.c
- sys/kern/mutex.c
- sys/kern/spinlock.c
- sys/kern/taskqueue.c
- sys/kern/tmpfs.c
- Add a new lock type (`LK_BLOCK`) that represents ordinary mutexes that use turnstiles
- Adjust lock type values so that it is possible to check that the caller doesn't try to set the lock type themselves in `mtx_init` and `spin_init`
> Adjustments to lock_type_t

- include/sys/callout.h
- include/sys/thread.h
- sys/kern/sleepq.c
- sys/kern/thread.c
- sys/tests/callout.c
- sys/tests/sleepq.c
* Move thread sleep callout from stack to thread structure.
* Review `tests/sleepq.c`
* Move one callout in `tests/callout.c` to bss section.
> Move callout structures from stack to dynamically or statically allocated memory

- include/sys/signal.h
- sys/kern/proc.c
- sys/kern/signal.c
- sys/mips/signal.c
This only led to errors in sig_kill where we forgot to unlock it.
> Don't unlock the process in sig_kill.

- sys/kern/proc.c
- sys/kern/thread.c
If the parent of an exiting child ignores SIGCHLD, the child shouldn't leave any state for the parent to reap.
> Implement auto-reap.

- sys/kern/tmpfs.c
- sys/kern/vfs_vnode.c
When a file had been truncated (e.g. while opening a file with `O_TRUNC` flag) its mode was also removed. Invalid setting in `vattr_t` was the cause.
The second problem was that file type was omitted while changing permissions.
> Fix two bugs related to file modes

- include/sys/device.h
- sys/kern/device.c
- sys/mips/gt64120.c
* `gt_pci_release_resource` now calls `device_remove_resource`, so deallocated resource does not stay on `dev->resources` tail queue (note that `gt_pci_alloc_resource` calls `device_add_resource`, which adds a newly allocated resource to `dev->resources`)
* `device_alloc` now calls `TAILQ_INIT(&dev->resources)` (another bug fixed?)
Fixes #685
> Remove resource from device before deallocation

- include/mips/kasan.h
- sys/mips/boot.c
There is a mistake that PDE (page directory entry) is described as PTE (page table entry) in KASAN's code.
> KASAN: rename PTE to PDE in boot code

- sys/kern/kmem.c
A race is possible where thread 1 call `kmem_free()` and is preemted
right after `vmem_free()`. Then, thread 2 calls `kmem_alloc()` and
allocates the piece of address space just freed. Then, thread 1
marks the allocated addresses as invalid and unmaps them from the
kernel pmap.
By moving the call to `vmem_free()` to the very end, we make sure
that we 'own' the piece of address space until we're done with the
bookkeeping.
> Fix race between kmem_free() and kmem_alloc().

- bin/utest/fork.c
- sys/kern/proc.c
Currently, if a process that ignores `SIGCHLD` forks and waits for the child to exit, it will wait forever, but it can happen for 2 different reasons:
- If the child exits before the parent calls `wait()`, `do_waitpid` will fail to find a child process matching the criteria (because there are no children at all) and will wait until a child changes state, which will never happen.
What should happen: `do_waitpid` should notice that there are not child processes matching the criteria and return immediately with `ECHILD`.
- If the call to `wait()` happens before the child exits, the parent will wait until a child changes state, but the child will not notify the parent in `proc_exit`, because `auto_reap` will be true.
What should happen: the child should notify the parent unconditionally in …
> Auto-reap fixes

- include/sys/bus.h
Remove bus_space_read_1 that was defined 2 times.
> remove duplicated #define

- include/sys/klog.h
- include/sys/thread.h
- include/sys/time.h
- sys/debug/__init__.py
- sys/debug/klog.py
- sys/debug/struct.py
- sys/kern/klog.c
- sys/kern/ktest.c
- sys/kern/sched.c
- sys/kern/timer.c
- sys/tests/klog.c
- sys/tests/sched.c
- sys/tests/thread_exit.c
- sys/tests/thread_stats.c
Changing the representation of how we store time in kernel to more accurate, which give higher precision (2^-64 ≈ 5 * 10^-20 (bintime) instead of 10^-6 (timeval)).
> Replacing timeval with bintime in kernel.

- include/mips/config.h
- include/sys/time.h
- lib/libc/sys/gettimeofday.c
- sys/debug/struct.py
- sys/kern/clock.c
- sys/kern/timer.c
- sys/mips/timer.c
- sys/tests/thread_stats.c
After replacing timeval by bintime some functions/structures will not be used anymore. Functions related only with timeval are duplicated e.g. timeval_add, timeval_clear.
> Removing unused macros and function duplications related with time.

- include/sys/time.h
- sys/kern/clock.c
- sys/kern/time.c
- sys/kern/timer.c
Changing value  **clk_tck** to 1000, cause our system tick take 1ms.
Moving **tm2sec** to more appropriate file for this type of function.
> Fixing clk_tck definition & moving tm2sec to time.c

- include/sys/device.h
- sys/drv/atkbdc.c
- sys/drv/ns16550.c
- sys/drv/pit.c
- sys/drv/rtc.c
- sys/drv/stdvga.c
- sys/kern/bus.c
- sys/kern/clock.c
- sys/mips/gt64120.c
- sys/mips/rootdev.c
* fix `bus_generic_probe` -- now it initializes only devices in correct _devclass_
* use _devclass_ interface for device initialization
* introduce new member of `device_t` for access to _devclass_
* remove `gt_pci_bus` and `gt_pci` global references
* stop using `SYSINIT_ADD` for device initialization
* use `bus_generic_probe` everywhere where it is possible
> Use devclasses for device initialization

- .gitignore
- build/arch.aarch64.mk
- build/tools.mk
- launch
- launcher/__init__.py
- sys/Makefile
- sys/aarch64/boot.c
- sys/aarch64/rpi3.ld
- sys/aarch64/start.S
Use `LINUX_BOOT_ABI` for AArch64.
QEMU assumes the .img files are the Linux. We need `LINUX_BOOT_ABI` for RPI3 support.
> Use LINUX_BOOT_ABI for AArch64.

- include/aarch64/exception.h
- sys/aarch64/Makefile
- sys/aarch64/boot.c
- sys/aarch64/evec.S
- sys/aarch64/genassym.cf
According to sys/arm64/arm64/exception.S from FreeBSD we only need to handle:
- Synchronous EL1h
- IRQ EL1h
- Synchronous 64-bit EL0
- IRQ 64-bit EL0
> AArch64 exceptions.

- sys/kern/vm_physmem.c
Fix off-by-one error in `vm_physmem` found in #743.
> Fix off-by-one error in vm_physmem.

- sys/aarch64/interrupt.c
When I bit is set then exceptions are masked.
> Fix cpu_intr_disabled

- include/mips/pmap.h
- sys/mips/boot.c
- sys/mips/ebase.S
- sys/mips/pmap.c
* Treat kseg0 as direct map for free.
* Remove workarounds.
> Revert almost the greatest idea in MIPS pmap

- bin/utest/fd.c
- bin/utest/fpu_ctx.c
- bin/utest/misbehave.c
- bin/utest/mmap.c
- bin/utest/pgrp.c
- bin/utest/sbrk.c
- bin/utest/signal.c
- bin/utest/wait.c
Add void to function without arguments in `utest`.
In C `foo(void)` is different than `foo()`. Second variant could take any number of parameters of unknown types.
> Add void to function signatures in utest

- sys/kern/pool.c
- sys/kern/vmem.c
On _AArch64_ `vmem_t` doesn't fit on one page.
> Increase P_VMEM pool size for vmem_t

- sys/kern/timer.c
Do not dereference NULL address when timer is not found.
> Handling the lack of a timer in tm_reserve

- include/sys/klog.h
- include/sys/ringbuf.h
- include/sys/termios.h
- include/sys/tty.h
- include/sys/ttydefaults.h
- launch
- launcher/__init__.py
- sys/drv/ns16550.c
- sys/kern/Makefile
- sys/kern/klog.c
- sys/kern/ringbuf.c
- sys/kern/tty.c
- sys/mips/timer.c
- Add default control characters to `ttydefaults.h`
- Add `ringbuf_reset()` function
- Add launcher option to run `socat` in raw mode
- Replace `/dev/uart` with a terminal device
- Remove unneeded NS16550 UART code
- Implement basic TTY device with an asynchronous serial device driver interface
> Basic TTY implementation (raw mode only)

- include/sys/thread.h
- sys/kern/sleepq.c
Now we hold a spinlock all the way from entering a thread into the sleepq until `sched_switch()`, so we can't receive a signal
or be woken up in the middle.
This also eliminates the need for 2 signal checks and fixes a bug where we didn't leave the sleepq if the second signal check finds that we should interrupt the sleep:  https://github.com/cahirwpz/mimiker/blob/5073f58cd2cf623713f7f0e9614bb66e7208b563/sys/kern/sleepq.c#L171-L174
> Get rid of the TDF_SLEEPY flag.

- include/sys/signal.h
- sys/kern/exception.c
It wasn't clear to me that calling `sig_post()` multiple times won't make us lose pending signals. It turns out it's safe, but it's far from obvious. I have added some comments to help future readers of the code.
> Clarify behavior of sig_post().

- include/sys/thread.h
- sys/kern/signal.c
- sys/kern/thread.c
This gives us the nice property that if `sig_pending()` returns a signal, then that signal isn't ignored. I will be using this property in the future.
> Discard pending signals when ignoring them via sigaction().

- include/sys/pci.h
- sys/drv/stdvga.c
- sys/kern/pci.c
Make device bars appear sequentially in the PCI device structure
so that a driver does not have to check which bar is vaild and which is not.
> Sequential bar numbers.

- include/sys/syscallargs.h
- sys/kern/syscalls.c
- sys/kern/syscalls.master
- sys/script/makesyscalls.sh
That change introduce wrappers for arguments that allow to pass something smaller than register.
All arguments inside `_args_t` are packed into union of `register_t` and real argument so now we can use `memcpy` for creating arguments from CPU context in machine dependent layer of syscalls without problems.
It's necessary for _AArch64_ where arguments are smaller than registers.
> Size independent arguments for syscall

- include/sys/proc.h
- include/sys/signal.h
- include/sys/tty.h
- sys/kern/proc.c
- sys/kern/signal.c
- sys/kern/tty.c
- Add concepts of controlling tty and foreground pgrp
- Implement ioctls for getting and setting foreground pgrp
- Implement background wait in `tty_{read,write}()`
- Add `SIGTTIN` and `SIGTTOU` signals
> TTY: Introduce concepts of controlling terminal and foreground process group

- sys/aarch64/copy.S
Restore link register in `copyin`, `copyout`, `copyinstr`, `copyerr`.
> Restore link register in copy.S.

- include/sys/pci.h
- sys/drv/stdvga.c
- sys/kern/pci.c
Abandon the current approach which (incorrectly) tries to provide sequential bar numbers to a device driver. We should only rely on physical bar identifiers, which drivers must be aware of.
> Only use physical bar numbers.

- launcher/__init__.py
At this point our TTY subsystem has enough features to handle raw input.
> launcher: run socat on /dev/tty1 in raw mode by default.

- include/sys/pci.h
- sys/aarch64/rootdev.c
- sys/drv/stdvga.c
- sys/kern/pci.c
- sys/mips/gt64120.c
- sys/mips/rootdev.c
- Disable memory/IO accesses during PCI bar sizing (as required by the specification).
- Add function which enables bus master mode for a device.
- Write address to a BAR register while activating a `RT_IOPORTS` resource (RTL8139 and USB controller use `RT_IOPORTS` bars).
> Enhance configuration space handling.

- include/sys/vm.h
- sys/aarch64/pmap.c
- sys/mips/pmap.c
Now pv_list in vm_page_t structure isn't protected by any mechanism. That can lead to many races when we will try to share our resources. This PR will introduce lock for all pv_list to protect our data and in the same time - to save some memory by using only one lock for all pv_list data structures.
> Implement locking mechanism for pv_list in vm_page_t structure

- sys/kern/tmpfs.c
Root of tmpfs had no inforamation about owner and group.
> Repair tmpfs root attributes

- sys/kern/devfs.c
- sys/tests/Makefile
- sys/tests/devfs.c
There was an oversight in #883: when a devfs directory node is unlinked, the devfs layer is responsible for freeing the directory node after all references to the vnode are gone (i.e. in `VOP_RECLAIM()`), but we didn't provide an implementation of `VOP_RECLAIM()`.
I have also thrown in a devfs directory removal test.
> Reclaim devfs directory nodes.

- sys/aarch64/pmap.c
> AArch64: fix pmap_copy_page

- include/sys/tty.h
- sys/drv/ns16550.c
- sys/kern/tty.c
This PR kicks off a series of (hopefully small) PRs with an end goal of implementing pseudoterminals.
Why we need this PR:
`write()` calls on a PTY master device can block due to the slave device's input queue being full. We need some means of notifying the master that space has become available.
> tty: notify driver when there's space in the input queue.

- include/sys/tty.h
- sys/drv/ns16550.c
- sys/kern/tty.c
- Add an open count to the `tty_t` structure
- Notify the driver when the open count goes from 0 to 1 and from 1 to 0
- Unify common parts of `tty_vn_open()` and `dev_tty_open()`
- Add helper function for making TTY devfs entries
> Track TTY open() and close() calls.

- sys/kern/tmpfs.c
- sys/kern/vfs_syscalls.c
We should check permission to write to directory when we create or remove files and directories.
Now we also should change permissions of `/tmp` dir because everyone should have permission to create files in it. (In the future this directory should have also sticky bit set so users can't delete others' files).
> Checking permission to perform write operation on directory

- include/sys/filio.h
- sys/kern/tty.c
The `FIONREAD` ioctl returns the number of bytes ready to be read. It will be useful for testing canonical mode, to check that no bytes are ready to be read until a complete line is typed.
> Add FIONREAD ioctl

- sys/mips/gt64120.c
Use `IO_ICUSIZE` instead of sort-of random `ICU_LEN`.
> Remove unnecessary ICU_LEN from gt64120 driver

- include/sys/cdefs.h
- include/sys/mimiker.h
- sys/libkern/Makefile
- sys/libkern/copystr.c
Some functions can't be instrumented because of stack issues. The compilers (both GCC and Clang) provide an attribute to specify that a particular set of instrumentations should not be applied to a function, so we won't have to write extra Makefile rules anymore.
> Add an attribute to disable the compiler instrumentation

- sys/kern/pci.c
- sys/mips/gt64120.c
Fix memory bar sizes relying on the PCI 3.0 specification.
> Round up memory bars to the page size boundary.

- include/aarch64/tlb.h
- sys/aarch64/pmap.c
- sys/aarch64/tlb.c
Use virtual address instead of physical address in `tlb_invalidate`.
`TLBI VAE1IS` & `TLBI VAAE1IS` require virtual address as argument.
Fix kernel-space `pmap_page_copy` test for _AArch64_ - #932.
> AArch64: use virtual address instead of physical address in tlb_invalidate.

- bin/utest/sbrk.c
Fix user-space `sbrk` test for _AArch64_ - #932.
> AArch64: fix user-space sbrk test.

- bin/utest/mmap.c
Fix user-space `mmap` test for _AArch64_ - #932.
> AArch64: fix user-space mmap test.

- sys/tests/vm_map.c
Fix kernel-space `findspace` test for _AArch64_ - #932.
> AArch64: fix kernel-space findspace test.

- include/paths.h
- include/pwd.h
- include/sys/file.h
- include/sys/param.h
- include/sysexits.h
- include/unistd.h
- lib/libc/gen/execlp.c
- lib/libc/gen/ttyname.c
I added `sysexits.h` and `execlp()` functions.
I had to add macro `_KERNEL` in `file.h` to allow using it in userspace. (e.g `sys/mutex.h` cannot be included in userspace programs)
This changes are required by #945
> Login: changes in libc and headers

- sys/kern/file_syscalls.c
`do_fstat` was using `fdtab_get_fd` with flag `FF_RED` for no reason.
needed by #945
> Allow fstat() on file descriptors without read access

- sys/kern/vfs_syscalls.c
I forgot to handle possible errors generated by call to `VOP_GETATTR`.
> Handle errors generated by VOP_GETATTR

- sys/kern/proc.c
Sessions struct weren't zeroed on creation, so the field `tty_t *s_tty` could contain a garbage and thus every check like [this](https://mimiker.ii.uni.wroc.pl/source/xref/mimiker/sys/kern/tty.c#1091) or [this](https://mimiker.ii.uni.wroc.pl/source/xref/mimiker/sys/kern/proc.c?r=1a7dabd3#362) wasn't working as expected.
> proc: zero session structs before use

- include/sys/klog.h
- sys/kern/klog.c
There is a harmless race on the variable `klog.mask`. Although it is set under a spin lock, there is no synchronization when reading it.
Found by KCSAN.
> klog: fix race

- sys/kern/vfs_syscalls.c
We should drop the reference to the old cwd and acquire the reference to the new one while changing directory.
There was a bug causing that the new cwd was released twice.
> fchdir: release old cwd vnode

- include/sys/pci.h
- sys/kern/pci.c
Introduce `subclass_code` and `progif` in `pci_device`.
> Read subclass code and programming interface fields from PCI configuration space.

- include/sys/kmem.h
- sys/aarch64/rootdev.c
- sys/kern/bus.c
- sys/kern/initrd.c
- sys/kern/kmem.c
- sys/mips/uart_cbus.c
`kmem_alloc_contig` is mainly geared toward device driver programmers. It's main use case is to allocate memory for DMA transfers.
> kmem: allocate contiguous physical memory

- build/common.mk
- include/aarch64/armreg.h
- lib/libc/aarch64/genassym.cf
- lib/libc/gen/aarch64/setjmp.S
- sys/aarch64/evec.S
- sys/aarch64/genassym.cf
- sys/aarch64/interrupt.c
- sys/aarch64/switch.S
- sys/aarch64/trap.c
Disable interrupts in `user_exc_leave`.
> AArch64: disable interrupts in user_exc_leave.

- include/aarch64/armreg.h
- lib/libc/aarch64/genassym.cf
- lib/libc/gen/aarch64/longjmp.c
- sys/aarch64/context.c
- sys/aarch64/evec.S
Validate status register in setcontext syscall.
It fixes sigaction_with_setjmp, mmap_prot_none, mmap_prot_read from #932.
> AArch64: validate status register in setcontext syscall.

- include/aarch64/pte.h
- sys/aarch64/boot.c
- sys/aarch64/pmap.c
Map kernel pages with `VM_PROT_NONE` without read permissions.
It fixes pmap_kenter and rmbits from #932.
> AArch64: map kernel pages with VM_PROT_NONE without read permissions.

- include/sys/vm.h
- include/sys/vm_object.h
- include/sys/vm_physmem.h
- sys/kern/kmem.c
- sys/kern/vm_map.c
- sys/kern/vm_object.c
- sys/kern/vm_physmem.c
It should fix #968 issue. I investigated every call to `vm_page_free` and made sure there's corresponding call to `pmap_remove` or `pmap_kremove`.
> Fix deadlock caused by call to pmap_page_remove in pm_free_from_seg

- sys/kern/proc.c
From the specification of `_Exit()` in POSIX (https://pubs.opengroup.org/onlinepubs/9699919799/functions/_Exit.html):
> If the exit of the process causes a process group to become orphaned, and if any member of the newly-orphaned process group is stopped, then a `SIGHUP` signal followed by a `SIGCONT` signal shall be sent to each process in the newly-orphaned process group.
> pgrp_maybe_orphan(): send SIGHUP + SIGCONT to all members of pgrp if any member is stopped

- sys/kern/proc.c
`fdtab_drop()` can acquire `tty_t::t_lock` further down the call chain, but we depend on being able to acquire `proc_t::p_lock` while holding `tty_t::t_lock`, so we can't acquire `tty_t::t_lock` while holding `proc_t::p_lock`, which is exactly what might happen if we call `fdtab_drop()` while holding `proc_t::p_lock`.
I have also moved the call to `vm_map_delete()`, since we don't need `p_lock` for that either.
Fixes #1027
> proc_exit: don't call fdtab_drop() while holding p->p_lock

- sys/drv/pit.c
The HZ2BT operation use a 64-bit division, which can be expensive, use the already calculated value for `HZ2BT(freq)`.
> Removing the expensive HZ2BT operation in pit gettime

- include/sys/mutex.h
- include/sys/proc.h
- sys/kern/mutex.c
- sys/kern/proc.c
Right now there's only one place where we're acquiring multiple `pg_locks`, and we already happen to hold `all_proc_mtx` there, so we can simplify the locking rules by requiring that `all_proc_mtx` be held in order to acquire multiple `pg_locks`.
> Simplify locking rules around pgrp_t::pg_lock

- include/sys/ringbuf.h
- sys/kern/ringbuf.c
- sys/tests/ringbuf.c
this function is needed to be used in coming rtl8139's PR
> ringbuf_move[n]b to move data between two ringbuffers

- sys/kern/mmap.c
- sys/kern/vm_map.c
Asserting that we are destroying the range between a segment can prevent us from some future bugs.
The max for `do_munmap` is unnecessary, cause `vm_map_find_segment` already guarantee that `addr >= start`.
> Assert for vm_segment_destroy_range and simplyfing do_munmap

- bin/utest/exceptions.c
- bin/utest/main.c
- bin/utest/utest.h
- include/aarch64/armreg.h
- sys/aarch64/boot.c
- sys/aarch64/trap.c
- sys/tests/utest.c
* Add tests for user-space exception handler.
* Enable alignment checking - see [SCTLR_EL1](https://developer.arm.com/documentation/ddi0595/2020-12/AArch64-Registers/SCTLR-EL1--System-Control-Register--EL1-?lang=en#fieldset_0-25_25) register.
> AArch64: exc tests.

- include/sys/bus.h
- include/sys/pci.h
- sys/kern/bus.c
- sys/mips/82371AB.c
Convert `PCI_BUS_METHODS` and `BUS_METHODS` into functions.
> drivers: Convert PCI_BUS_METHODS and BUS_METHODS into functions.

- bin/utest/time.c
- sys/aarch64/sigcode.S
- sys/aarch64/signal.c
- sys/kern/exec.c
- sys/mips/sigcode.S
- sys/mips/signal.c
- sys/tests/fdt.c
This PR fixes a couple of issues I encountered while trying to compile and run the kernel with `-O2`.
> Fix build & test run with -O2 optimization flag

- include/dev/scsi.h
- include/dev/uhci.h
- include/dev/uhcireg.h
- include/dev/umass.h
- include/dev/usb.h
- include/dev/usbhid.h
The presented header files are required by #935.
Presented changes (regarding original files):
- `scsi.h`:
- `length` and `addr` fields aren't expressed in byte units (i.e. instead of `uint8_t addr[4]` we have `uint32_t addr`). This simplifies little endian <-> big endian conversions.
- I've added the `SID_FORMAT()` macro (used in drive identification).
- `uhci.h`: this is simply a subset of the original file (with a few stylistic changes).
- `uhcireg.h`:
- I've added `PCI_USB_CLASSCODE` and `PCI_USB_SUBCLASSCODE`.
- I've added ` UHCI_PORTSC()` instead of `UHCI_PORTSC{1,2}` (The UHCI specification allows more than two root hub ports).
- I've added `UHCI_PORTSC_ONE` which is used in root hub port detection (I don't assume any specific number of root hub ports).
- `umass.h`: this file …
> Introduce basic USB related header files.

- include/sys/mutex.h
- include/sys/proc.h
- include/sys/spinlock.h
- sys/aarch64/pmap.c
- sys/kern/callout.c
- sys/kern/cred_checks.c
- sys/kern/dev_procstat.c
- sys/kern/devfs.c
- sys/kern/fork.c
- sys/kern/interrupt.c
- sys/kern/klog.c
- sys/kern/pool.c
- sys/kern/proc.c
- sys/kern/pty.c
- sys/kern/sched.c
- sys/kern/sleepq.c
- sys/kern/syscalls.c
- sys/kern/thread.c
- sys/kern/timer.c
- sys/kern/tmpfs.c
- sys/kern/tty.c
- sys/kern/turnstile.c
- sys/kern/vfs.c
- sys/kern/vm_physmem.c
- sys/kern/vmem.c
- sys/mips/pmap.c
- sys/tests/mutex.c
- sys/tests/turnstile_adjust.c
- sys/tests/turnstile_propagate_many.c
- sys/tests/turnstile_propagate_once.c
This is rather cosmetic change, but required by the lock dependency validator.
> Introduce MTX_DEFINE & SPIN_DEFINE macro

- sys/kern/malloc.c
Currently, if `strlen(s) > maxlen`, the copy will not be null-terminated.
> kstrndup(): always return null-terminated string.

- sys/kern/proc.c
If `pg == p->p_pgrp`, then `pg` must be non-`NULL` (since `p->p_pgrp` is always non-`NULL`), so the second check will make us return `EPERM`, making the first one unnecessary.
> Remove redundant check in session_enter()

- Dockerfile
- toolchain/gnu/config.mk
Debian packages are ready to use in my home directory on the server (`/home/jurb/`).
#999 is required to compile Mimiker under the new GCC version.
> Bump gcc version to 11

- include/signal.h
- lib/libc/gen/siginterrupt.c
- lib/libc/sys/signal.c
On Linux, FreeBSD and NetBSD (I haven't checked others) signal handlers set up using `signal()` do not interrupt system calls (i.e. make them return with `EINTR`). Instead, the system call is restarted after the signal handler runs (unless the system call has some data to return, in that case it just returns that data). The behavior can be changed using the `siginterrupt()` function.
> signal(): restart interrupted system calls by default

- include/sys/kasan.h
- sys/kern/vm_physmem.c
- sys/mips/boot.c
If we're not going to expand the shadow map in `vm_boot_alloc()`, at least let's add a check to prevent nasty bugs in the future.
> vm_boot_alloc(): don't let vm_kernel_end go past _kasan_sanitized_end

- bin/ksh/Makefile
```
/mimiker/bin/ksh/history.c: In function 'hist_execute':
/mimiker/bin/ksh/history.c:317:31: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
317 |                         q[-1] = '\n';
|                         ~~~~~~^~~~~~
/mimiker/bin/ksh/history.c:303:26: note: destination object of size [0, 9223372036854775807] allocated by 'strchr'
303 |                 if ((q = strchr(p, '\n'))) {
|                          ^~~~~~~~~~~~~~~
```
> ksh/history.c: silence warning during compilation with -O2

- launch
'-S' option shouldn't be supplied regardless of the command line options as is done now in `qemu: { options: {...`. Instead, it should only be included if the debug option ('-d') is supplied (as is done in `if getvar('config.debug'): self.options += ['-S']`. For now, '-S' is always present and thus `launch` doesn't work without '-d' (because the gdb window doesn't appear).
> Run mimiker without the debug option.

- include/aarch64/bus_defs.h
- include/mips/bus_defs.h
- include/sys/bus.h
- include/sys/bus_defs.h
- include/sys/rman.h
- launch
`include/$(ARCH)/bus_defs.h` only includes `include/sys/common_bus_defs.h` regardless of the value of `$(ARCH)`, therefore I've deleted these files and rename `include/sys/common_bus_defs.h` to `include/sys/bus_defs.h`. This solution is less ambiguous.
> Remove MD bus definitions.

- include/sys/vm.h
- include/sys/vm_object.h
- sys/kern/vm_map.c
- sys/kern/vm_object.c
* Added `vm_object_hold` function to hide reference counter and renamed `vm_object_free` to `..._drop`.
* Renamed (and removed anonymous struct) entry on `vm_object`'s page list in `vm_page`.
> Clean vm_object interface

- sys/kern/kmem.c
Ensure that input VA in `kva_map` is page aligned (as `kva_unmap` does).
Make `kmem_alloc_contig` more compact by using `kmem_map_contig`.
Make `kmem_map_contig` more compact by using `kva_map_page`.
> Ensure page alignment in KVM mapping routine and make "contig" functions more compact.

- sys/kern/pool.c
- Remove pool item constructors/destructors (they are never used).
- In `pool_alloc` when we allocate a new slab, we have to remove it from the empty list (thus the `else` statement has been removed).
- Fix `pool_alloc` signature.
- Fix `destory_slabs`, i.e. set `pg->slab` to NULL before releasing slab's pages in `kmem_free`, and update pool's statistics.
> Fix pool allocator.

- include/sys/file.h
- include/sys/uio.h
- include/sys/vnode.h
- sys/drv/dev_cons.c
- sys/drv/evdev.c
- sys/drv/rtc.c
- sys/drv/stdvga.c
- sys/kern/dev_null.c
- sys/kern/dev_procstat.c
- sys/kern/exec_elf.c
- sys/kern/exec_shebang.c
- sys/kern/file.c
- sys/kern/file_syscalls.c
- sys/kern/initrd.c
- sys/kern/pipe.c
- sys/kern/pty.c
- sys/kern/tmpfs.c
- sys/kern/vfs_vnode.c
- sys/tests/vfs.c
* Clean up file flags: they express allowed operations and I/O operation flags (nonblocking, append, ...)
Changes extracted from #1103.
> Move ioflags from VOP_READ/WRITE arguments into uio::uio_ioflags

- sys/kern/kmem.c
`kmem_map_contig` doesn't receive `size` in `PAGESIZE` units but rather in bytes, thereby the invocation within `kmem_alloc_contig` has to be changed.
> Fix kmem_map_contig invocation.

- sys/kern/pool.c
The `slab` member of the `vm_page_t` structure is a member of an anonymous union, thus we can't assume it has a known value when we start using this field.
> Remove an assert in add_slab.

- sys/kern/kgprof.c
This one assertion will help understanding entry conditions in `kgprof_tick`. We make here access to `_gmonparam` without taking a lock and it was confusing without knowing that this function is called under interrupts disabled.
> Add assertion in kgprof.c

- include/dev/usb.h
- include/sys/device.h
Introduce USB interfaces to implement by a USB bus driver.
The interfaces include:
- USB standard interface (i.e. standard transfer typed),
- USB standard requests interface,
- USB HID specific standard requests interface,
- USB Bulk-Only specific standard requests interface.
This PR contains changes introduced in #1112.
> Introduce USB interfaces.

- etc/.kshrc
This prevent `setwinsize` from running when recording a terminal session with `script`. 
We don't want it to run because if we do, then when playing the session back, the terminal will send us an escape sequence containing the cursor position, but since `setwinsize` isn't actually running (only the recording of its output), the escape sequence gets echoed by the shell after playback is finished, which looks ugly.
> Set window size on shell startup only if it isn't already set

- build/arch.aarch64.mk
- sys/Makefile
r.pi3 doesn't play well with compressed image - let's keep uncompressed version.
> build: keep kernel image after compression

- sys/kern/dtb.c
Bootloader can decide to load dtb into middle of random physical page and we need to deal with that inside kernel. For that purpose we can store offset of dtb for first phys page.
- store offset of dtb
- calculate mapping size for dtb including gap at the first page
> dtb: fix absolutely shitty behavior of bootloaders

- sys/kern/exec_elf.c
Remove unnecessary `bzero` call in `load_elf_segment`.
> elf: remove unnecessary bzero

- build/arch.aarch64.mk
bcopy: remove not alignment access to memory for AArch64.
Fixes #1097.
> aarch64/bcopy: remove not aligned access to memory

- sys/kern/pipe.c
Without this, processes sleeping on pipe I/O won't be interrupted by signals, which means e.g. that when a process in a background pipeline tries to read from the controlling terminal, processes in the pipeline that are sleeping on pipe I/O won't be stopped.
> Make pipe I/O operations interruptible by signals.

- toolchain/gnu/config.mk
- toolchain/qemu-mimiker/Makefile
* New toolchain version - 1.5.2
* Update gcc to 11.2.0
* Update binutils to 2.37
* Remove support to x86
x86 toolchain is not used by Mimiker since we don't support that architecture - let's remove support for that toolchain and reduce complexity and build time of tools.
Signed-off-by: Paweł Jasiak <pawel@jasiak.dev>
> Toolchain: bump binutils & gcc, remove x86

- include/aarch64/mcontext.h
- include/mips/mcontext.h
There is a handful of UC defines which are unused (in both architectures).
> Remove needless UC defines.

- sys/drv/Makefile
USB bus driver should be build unconditionally as we assume all boards to support it.
> [USB] Build bus driver unconditionally.

- launch
1. Number ttys from 0 (as hardware numerates uarts from 0).
2. Rename rip3 console to tty since `DevelRun` uses this name as the default tmux window if running without debugger.
> Launch tty renumbering and fix.

- .gitignore
- build/common.mk
- build/tools.mk
- sys/Makefile
Required by #1176.
We would like to support several (RISC-V, platform) setups having a single linker script for the kernel. To achieve this goal we can parametrize linker scripts whit constants exposed by genassym (see http://bxr.su/NetBSD/sys/arch/riscv/conf/kern.ldscript).
> Process kernel linker scripts using CPP.

- sys/kern/interrupt.c
FTTB, all interrupt handlers associated with a given interrupt event are equally important (we always set the priority to 0).
> [DEV] Remove interrupt handler priority.

- include/sys/interrupt.h
- sys/drv/bcm2835_rootdev.c
- sys/drv/malta_rootdev.c
- sys/kern/interrupt.c
`intr_root_filter` routine contains a redundant argument `arg`. It's completely needless (and not used) as a rootdev driver can pass any needed data through its state (accessed through `driver_t` structure).
> [DEV] Remove redundant argument from root interrupt handler.

- .gitignore
- launch
Required by #1176.
Renode has built-in support for SOCs generated using LiteX. We need it to simulate the VexRiscv platform.
Includes changes from #1185.
> Add Renode to launch.

- sys/kern/proc.c
- sys/kern/signal.c
- sys/kern/sleepq.c
- sys/kern/thread.c
`tid_t` is `uint32_t` aka `unsigned int` which uses `%u` as specifier for `printf`-like functions.
> [klog] fix klog format for tid_t

- include/riscv/asm.h
- include/riscv/mcontext.h
- include/riscv/types.h
Current RISC-V headers don't respect the fact that if double FP extension is supported then both `__riscv_f` and `__riscv_d` are defined.
> [RISCV] Fix FP defines.

- include/riscv/pte.h
- include/riscv/riscvreg.h
- sys/riscv/mcontext.c
Our RISC-V port relies on the headers taken from FreeBSD with modifications based on the corresponding NetBSD headers.
This PR contains changes from #1215.
> [RISCV] Introduce BSD RISC-V headers.

- lib/csu/aarch64/crt0.S
- lib/csu/mips/crt0.S
Both MIPS and Aarch64 refer to the nonexistent `prepare_program_stack` procedure as a reference to setting the program's environment.
> [csu] Fix ELF entry point description.

- lib/libc/sys/aarch64/sc_missing.S
`__sc_error` should behave as if the syscall returned `ENOSYS`.
> [Aarch64][libc] Fix missing syscall handling.

- toolchain/qemu-mimiker/Makefile
- toolchain/qemu-mimiker/debian/changelog
- toolchain/qemu-mimiker/debian/control
Mimiker will support both 32- and 64-bit RISC-V CPUs. For the 64-bit variant, the QEum system emulator will be used.
> [RISCV] QEmu: add 64-bit system emulator.

- include/sys/bus.h
- include/sys/device.h
- include/sys/interrupt.h
- sys/aarch64/timer.c
- sys/drv/82371AB.c
- sys/drv/atkbdc.c
- sys/drv/bcm2835_rootdev.c
- sys/drv/gt64120.c
- sys/drv/malta_rootdev.c
- sys/drv/ns16550.c
- sys/drv/pci.c
- sys/drv/pit.c
- sys/drv/pl011.c
- sys/drv/rtc.c
- sys/drv/rtl8139.c
- sys/drv/uhci.c
- sys/kern/bus.c
- sys/kern/device.c
- sys/kern/interrupt.c
- sys/mips/timer.c
With the arrival of RISC-V we finally have interrupt controllers that cannot be perceived as buses. Therefore, the current bus interface must be split into two separate interfaces:
- bus interface,
- interrupt controller interface.
> [dev] Interrupt controller interface.

- include/sys/fdt.h
- sys/kern/fdt.c
- sys/kern/main.c
We don't have to map the FDT blob to kva as it can be accessed through the direct map. The `FDT_change_root` and `FDT_get_physaddr` functions are used (currently only by RISC-V, see #1182) to provide the FDT module with a dmap address after building the direct map. (Note that the same will be done for Aarch64 when the code is changed to first read the memory boundaries and build dmap afterward.)
Besides, the PR removes a warning caused by aliasing violation.
> [dtb] Access FDT blob using dmap.

- sys/aarch64/signal.c
- sys/mips/signal.c
`ksiginfo_t` is a kernel-internal structure. The user should only be able to access the corresponding `siginfo_t` structure.
> [sig] Copy siginfo instead of ksiginfo when sending signals.

- include/sys/libkern.h
- sys/libkern/stdio/printf.c
`kasprintf` is a prinf-like function commonly used by device drivers e.q. in Linux. We came to the conclusion that it would be beneficial to have this function implemented in Mimiker. We already have a usage example in #1237 (in `plic_intr_name`).
> [libkern] Implement kasprintf.

- sys/kern/device.c
First, we need to start releasing the state allocated for a device if the attach is unsuccessful. Additionally, I moved allocation from probe to attach.
> [drv] Move device's state allocation and release to attach

- lib/csu/riscv/crt0.S
`argc` is an `int`, not a `long`. Such confusion causes troubles in a 64-bit system.
> [RISCV][lib] Fix argc setting.

- sys/drv/Makefile
- sys/drv/sifive_uart.c
The HiFive Unleashed board is equipped with a SiFive UART device, hence a driver is needed.
> [RISCV][drv] SiFive UART driver.

- sys/drv/litex_riscv_rootdev.c
The current convention assumed by simplebus is that the device node of the rootdev device points at the local interrupt controller.
> [RISCV][dev] Fix LiteX VexRiscv rootdev device node assignemnt

- include/sys/fdt.h
- sys/drv/simplebus.c
- It turns out that it's not that rare for a device to generate more 8 interrupts (e.g. plic and clint in HiFive Unleashed)
- Fix tuples allocation for interrupt cells
- Fix validation logic
- Fix tuple copying
> [drv] Fix simplebus.

- include/sys/pmap.h
- include/sys/uio.h
- include/sys/vm_map.h
- sys/aarch64/trap.c
- sys/gen/pmap.c
- sys/kern/main.c
- sys/kern/uio.c
- sys/kern/vm_map.c
- sys/mips/trap.c
- sys/riscv/trap.c
- sys/tests/uiomove.c
- sys/tests/vm_map.c
With the arrival of #1243, the kernel can only use wired memory mappings. This makes maintaining  `kspace` needles and the generic `vm_map` logic can be simplified to consider only user virtual memory maps.
> [vm] Remove kernel vm_map since all kernel mappings are wired

- sys/kern/initrd.c
We don't have to map the large initrd to kernel virtual memory as the entire archive can be accessed using dmap.
> [initrd] Access initrd using dmap

- include/riscv/riscvreg.h
It turns out that the `CSR_ZIMM` is faulty, e.g. it can classify an expression of the type `array_addr - imm` as a constant within the range [0, 31].
> [RISCV] Remove faulty CSR immediate macros.

- sys/riscv/boot.c
Whenever writing to the `satp` register we need to issue the `sfence.vma` instruction to ensure that the writing operation takes effect.
This fix causes the following `nop` instruction to always trigger an exception on both hardware platforms.
> [RISCV] Fix virtual memory boot phase entry.

- Dockerfile
- Makefile
- toolchain/gnu/config.mk
- toolchain/gnu/riscv64-mimiker-elf/Makefile
Although we ultimately want to switch entirely to LLVM toolchain, FTTB we rely on the GNU toolchain.
> [RISCV] Enhance the GNU toolchain to include RISC-V 64.

- sys/drv/plic.c
The HART hierarchy on our VexRiscv platform is very different from the one utilized in SiFive Unleashed. The PLIC driver must be adjusted to support the SiFive board.
> [RISCV][dev] PLIC support for SiFive Unleashed.

- sys/drv/simplebus.c
`sb_intr_to_rl` should return an error code.
> [dev] Fix return value of simplebus interrupt processing function.

- include/riscv/vm_param.h
- sys/aarch64/boot.c
- sys/kern/vm_physmem.c
- sys/riscv/boot.c
Currently, the target architecture must provide kernel page directories for the `vm_page_t` structs during the boot phase as physmem initialization cannot rely on the buddy system to allocate physical pages. This problem can be solved by relying on dmap to access the `vm_page_t` structs.
> [physmem] Access vm_page_t structs using dmap.

- wiki/docs/_Sidebar.md
This PR fixes the “Structure” link in the sidebar of the wiki, since it followed into the plaintext version of the document.
> Sidebar link fix 

- .github/workflows/default.yml
- build/arch.aarch64.mk
- build/arch.mips.mk
- build/arch.riscv.mk
- build/flags.kern.mk
- build/tools.mk
- include/sys/cdefs.h
- include/sys/mimiker.h
- lib/libc/stdlib/merge.c
- lib/libc/stdlib/qsort.c
- lib/libm/src/s_scalbn.c
- sys/kern/kasan.c
- sys/libkern/stdlib/qsort.c
- sys/riscv/boot.c
- sys/riscv/riscv.ld.in
- sys/riscv/start.S
- sys/riscv/trap.c
We'd like to switch to Clang exclusively and ditch support for GCC. Hence all Clang builds need to pass when compiled with KASAN and LOCKDEP. There're some minor differences between Clang and GCC wrt. routines they expect to be implemented by ASAN runtime.
> Enable KASAN on build with Clang

- sys/riscv/switch.S
In most cases a value of `sstatus` register as seen by user would be used to calculate if kernel should save FPU context.
When calling `ctx_switch` while returning from interrupt, in `t0` register there would be kernel context. That caused user `sstatus` register to be corrupted. Namely SPP was set to supervisor, so the kernel attempted to return to execute user code with kernel privileges. In turn that leaded to a completely non-intuitive looping while trying to handle `exec_page_fault`.
> [RISCV] Use sstatus register value from user context in ctx_switch

- Dockerfile
- Makefile
- build/arch.riscv.mk
- build/tools.mk
- include/sys/mimiker.h
- sys/aarch64/boot.c
- sys/kern/initrd.c
- sys/kern/proc.c
- verify-format.sh
Let's use Clang provided by https://apt.llvm.org - we can update it on demand without waiting for release of new stable Debian distribution. There's another motivation... new linker supports `--wrap` (as GNU ld does) which is useful to clean up KASAN code.
> Bump up GH Actions to Clang 14

- include/riscv/boot.h
- include/riscv/cpufunc.h
- include/sys/boot.h
- include/sys/fdt.h
- include/sys/mimiker.h
- sys/aarch64/board.c
- sys/aarch64/boot.c
- sys/gen/Makefile
- sys/gen/boot.c
- sys/kern/fdt.c
- sys/mips/board.c
- sys/mips/boot.c
- sys/riscv/board.c
- sys/riscv/boot.c
Main goal of this change is to unify how DTB is handled on AArch64 and RISCV architectures. In both cases DTB is moved to kernel `.bss` section, so it's kept together with other precious data that won't be freed during kernel lifetime. Thanks to that decision `fdt.c` could be cleaned up from workarounds.
Moreover this change moves common code for MD boot code into `gen/boot.c` and also fixes `__tp` inline assembly (should not indicate that "tp" register is modified, otherwise it could be restored).
> Move DTB to kernel bss section on boot

- Makefile
- build/arch.aarch64.mk
- launch
- lib/libc/sys/aarch64/sc_error.S
- sys/aarch64/trap.c
- sys/kern/klog.c
- sys/kern/signal.c
- toolchain/qemu-mimiker/Makefile
- toolchain/qemu-mimiker/debian/changelog
- toolchain/qemu-mimiker/patches/cmdline-set-dts-bootargs.patch
- toolchain/qemu-mimiker/patches/fix-virtual-clock-in-gdb.patch
- toolchain/qemu-mimiker/patches/gdbstub-stop-on-sigxcpu.patch
- toolchain/qemu-mimiker/patches/page-table-walk-for-gdb.patch
This needed a bunch of fixes for AArch64 namely due to new version of QEmu being more strict on unaligned accesses.
> Bump up QEmu version to 6.2.0

- build/tools.mk
CC already contains CCACHE so CPP and AS call ccache ccache cc
Signed-off-by: Paweł Jasiak <pawel@jasiak.dev>
> build/tools: call ccache cc instead of ccache ccache cc

- include/sys/kmem.h
- include/sys/vmem.h
- sys/kern/kmem.c
- sys/kern/vmem.c
- sys/tests/pmap.c
- sys/tests/vmem.c
It turns out that our current implementation of `vmem_free` assumes that only entire segments will be freed. This assumption makes the `size` argument useless as the size is contained in the corresponding boundary tag.
> [mem] Remove the size argument from vmem_free.

- include/sys/kmem.h
- include/sys/vmem.h
- sys/kern/kmem.c
- sys/kern/vmem.c
The new implementation of the general purpose kernel memory allocator (#1323) needs a way to fetch the size of a selected vmem segment.
> [mem] Add a procedure to obtain the size of a pointed vmem segment.

- sys/gen/pmap.c
With the current assignment of lock classes, we have a cycle between `pool::pp_mtx` and `pmap::mtx`. The problem is as follows:
1. A call to `pool_alloc` can run out of segments with free items. This results in a kernel memory allocation (`kmem_alloc`) which maps a memory range using `pmap_kenter` (`pool::pp_mtx` -> `pmap::mtx`).
2. Whenever entering a pageable mapping to pmap `pma_enter` gets called. For each pageable mapping of a page, we maintain a physical-to-virtual entry (`pv_entry_t`) which is allocated from a dedicated pool (pmap::mtx` -> `pool::pp_mtx`).
However, the kernel only uses wired memory, thereby, introducing a separate lock class for kernel pmap solves the problem.
> [lockdep] Create a separate lock class for kernel pmap.

- include/sys/kmem.h
- include/sys/kmem_flags.h
- include/sys/pmap.h
- include/sys/vm.h
- include/sys/vmem.h
- sys/aarch64/boot.c
- sys/gen/pmap.c
- sys/kern/kasan.c
- sys/kern/kmem.c
- sys/kern/tmpfs.c
- sys/kern/vm_physmem.c
- sys/kern/vmem.c
- sys/mips/boot.c
- sys/riscv/boot.c
- sys/tests/pmap.c
- sys/tests/vmem.c
The primary problem with our current boundary tag allocation solution which is based on the pool allocator is that it creates a cyclic dependency between `pool` and `vmem`. If a pool happens to run out of free items in slabs, it calls `vmem` to allocate kernel virtual address space. However, if at that time `vmem` runs out of boundary tags, we reenter `pool_alloc` and panic due to an attempt to acquire a nonrecursive mutex for the second time. Moreover, changing the allocation scheme to allocate new slabs from some other area (e.g. `dmap`) doesn't fix all problems as there's still a cycle between vmem's and boundary tag pool's lock (which is sometimes detected by `lockdep`).
This PR contains changes introduced in #1327.
> [vmem] Boundary tag allocator.

- sys/drv/pci.c
Unfortunately, along with removing the resource manager (#1322) we have violated the alignment of PCI BARs. If BAR alignment is too small, the lower bits are ignored and we end up with a virtual address accessing some other parts of the configuration space.
> [dev] BAR address should be size-aligned.

- contrib/evtest/Makefile
If we call make recursively from `evtest` during the download phase, the build fails while obtaining dependencies for `evtest.c` as the sources aren't patched yet.
> [evdev] Fix evtest build.

- sys/kern/devfs.c
For seekable devices read and write operations might need to take the `f_offset` into account when performing reads or writes. Up until this PR the `uio_offset` field of `uio_t` passed to `d_read` and `d_write` methods was always set to zero. This PR sets it to the value of `file_t`'s `f_offset`, which represents the position of a cursor in a given file.
> Update uio_offset in devfs read/write operations

- include/sys/mutex.h
- sys/debug/sync.py
- sys/kern/lockdep.c
- sys/kern/mutex.c
- sys/kern/sleepq.c
- sys/kern/thread.c
- sys/kern/turnstile.c
So far lockdep was not enabled for spin mutexes. This PR changes that, although some spin mutexes need to be marked as `NODEBUG` since there's a mess with `td_lock` and `sc_lock` acquire order.
> Enable lockdep checking for almost all spin mutexes

- sys/kern/ustack.c
The current code assumes that malloc's `ALIGNMENT` is divisible by `STACK_ALIGN`. Although it turns out to be always valid for the present implementation, this assumption should be dropped.
> [exec] Fix user stack setup.

- include/dev/uhci.h
- sys/drv/uhci.c
The current code attempts to acquire blocking locks while holding a spin lock. The solution is to move IRQ handling into an ithread context.
> [usb] Fix UHCI USB host controller driver.

- build/flags.kern.mk
- sys/kern/kcsan.c
Sad observation is that KCSAN is supported by Clang only for aarch64 architecture.
> Fix kernel concurrency sanitizer under Clang

- include/aarch64/syscall.h
- include/mips/syscall.h
- include/riscv/syscall.h
- include/sys/klog.h
- include/sys/malloc.h
- include/sys/sysent.h
- sys/aarch64/trap.c
- sys/gen/Makefile
- sys/gen/syscall.c
- sys/mips/trap.c
- sys/riscv/trap.c
Why we have three versions of `syscall_handler` when we can have only one? Let's move `syscall_handler` to `sys/gen/syscall.c`!
> Unify syscall_handler for all three architectures

- sys/aarch64/boot.c
The bug is also present when compiled with Clang, but apparently does not crash the kernel.
Real size of kernel bss section must cover copied dtb as well.
> Fix crash during bootstrap when compiled with GCC

- include/sys/sched.h
- sys/kern/interrupt.c
- sys/kern/sched.c
- sys/kern/sleepq.c
As reported by @MichalBlk a recent change https://github.com/cahirwpz/mimiker/commit/dedbf1c51e4f9df92fd40d39b40749df608eca9a introduced a bug that could cause the kernel to make an attempt to switch out while executing `preempt_enable` from interrupt filters. This PR attempt to fix it.
> preempt_enable could switch out with interrupts disabled

- include/limits.h
- include/stdio.h
- include/stdlib.h
- include/sys/ioctl.h
- lib/libc/stdio/fmemopen.c
- lib/libc/stdlib/llabs.c
- lib/libc/string/aarch64/bcopy.S
- lib/libc/sys/creat.c
This PR adds functions, defines and fixes needed for porting suckless sbase:
- POSIX ARG_MAX, NAME_MAX, PATH_MAX values
- fmemopen()
- llabs()
- add missing include in include/sys/ioctl.h
- fix for aarch64/bcopy.S (memmove function)
- creat() - wrapper for open syscall
> New functions and changes needed for suckless sbase

- include/sys/syslimits.h
- sys/kern/kmem.c
- sys/kern/malloc.c
ARG_MAX value is changed from 3072 to 65536, `kva_map` and `kfree` are fixed
> Fix kernel memory allocation on large blocks

- include/sys/sleepq.h
- sys/drv/rtc.c
- sys/kern/callout.c
- sys/kern/condvar.c
- sys/kern/interrupt.c
- sys/kern/signal.c
- sys/kern/sleepq.c
- sys/kern/time.c
- sys/tests/sleepq.c
- sys/tests/sleepq_abort.c
- sys/tests/sleepq_timed.c
- sys/tests/thread_stats.c
- sys/tests/turnstile_adjust.c
As the current sleepq interface lacks any mechanism to lock the destination chain before calling the appropriate wait function, we at least need a way to release a provided lock before falling asleep.
The `sleepq_lock` mechanism will be introduced as part of merging #1367.
Required by `sigtimedwait` (see #1320).
> [sleepq] Add a mutex to the sleepq wait interface.

- bin/utest/cred.c
- sys/kern/syscalls.c
`getresuid` and `getresgid` return EFAULT when some address passed as argument is invalid. NULL value is also treated as invalid addres. This PR allows to pass NULL value as an argument for these syscalls (to retrieve only uids or gids for which non-NULL address is provided).
In manual entry ([getresuid(2)](https://www.freebsd.org/cgi/man.cgi?query=getresuid&sektion=2&n=1)) there is not specified what should happen if we pass NULL addres to these functions. Maybe that is the reason why we had choose to return error in such cases in the past.
> Fix error returned from getresuid and getresgid 

- .gitignore
- .gitmodules
After building Mimiker git status shows changes in submodules. I they shouldn't be visible.
> git: ignore changes in submodules

- launch
- requirements.txt
- verify-pycodestyle.sh
~I had a problem with launch script due to an update of API made in `libtmux v0.17.0`. (Accessing pane id is done in a different way now.) I have updated the launch script to determine which version is used and to access pane id using the right way.~
1. Ignore python files in current python venv
2. Pin versions of packages in `requirements.txt` (proposed versions work for me. Tested on Python 3.9 and 3.10.)
> Update python files

- sys/kern/vm_map.c
I have found, that checks of protection bits in `vm_page_fault` are done wrong. On aarch64 the `fault_type` has always set `VM_PROT_READ`. Then if access was read, then it didn't trigger any of these checks (because both read and write prot was set).
I have also added the check for exec bit.
> vm: Fix prot check in vm_page_fault

- .gitignore
I want to add clangd files to `.gitignore` to make working easier when using LSP.
Besides that change I am wondering if it is easy to add support for clangd in Mimiker. We currently have support for ctags and generate files for them. Clangd requires a file `compile_commands.json` which describes how to build the project (it can be generated with [`bear`](https://github.com/rizsotto/Bear) and I think we can consider adding some rule that will do that to Makefile).
> Add clangd files to `.gitignore`

- sys/kern/proc.c
`p_args` was freed different poll than it was allocated on.
> proc: Free `p_args` from proper kmalloc pool

- .github/workflows/default.yml
GitHub Actions runners were moved to another server with single core performance lower than the previous one. Previously they were run in virtualized environment with 4 cores and 8 hardware threads. Now they're running on 12 cores and 24 hardware threads machine.
Though total performance is higher on newer server, according to https://www.cpubenchmark.net/compare/3106vs2051/Intel-Xeon-Silver-4110-vs-Intel-Xeon-E5-2620-v2 single core performance is ~17% lower. Hence the timeouts have to be adjusted accordingly.
> Increase timeouts due to test environment changes

- sys/mips/trap.c
Add new cases to switch in `kern_trap_handler`.
> mips: add EXC_TLB{RI,XI} to trap handler

- contrib/sbase/Makefile
- include/sys/syslimits.h
- include/unistd.h
- lib/libc/gen/gethostname.c
- lib/libc/gen/sethostname.c
This PR adds the following missing tools from suckless sbase:
* `hostname` with `gethostname` and `sethostname` function stubs
* `getconf`
> sbase: add getconf and hostname

- contrib/sinit/patches/series
- contrib/sinit/patches/sinit.patch
- include/sys/ttycom.h
- sys/kern/tty.c
This PR adds `TIOCNOTTY` ioctl, which is used to disassociate the controlling terminal from a process. This ioctl should be used in `sinit.c`, so that a controlling terminal can be disassociated in the init process and later acquired in `getty` (related PR: https://github.com/cahirwpz/mimiker/pull/1390).
> tty: add TIOCNOTTY ioctl

- sys/tests/sleepq_timed.c
>    char name[20];
>    snprintf(name, sizeof(name), "test-sleepq-waiter-%d", i);
thread name written by snprintf has 20+ characters. name has space for 20 characters including \0. As a result thread name is always truncated to test-sleep-waiter-.
> [ktest] fix thread name buffer size

- sys/kern/vm_map.c
By skipping some operations in CoW handling procedure, we can reduce the number of copies even more. When some amap is the only owner of the anon during a page fault CoW scenario, this anon doesn't need to be copied.
> Reduce number of page copies

- lib/libc/sys/select.c
This PR provides `pselect` syscall implementation. Since the operation of `pselect` and `select` is almost identical, I reorganized the `lib/libc/sys/select.c` file, so that:
* `pselect` contains all the core implementation
* `select` converts its `struct timeval` argument to `struct timespec` and calls `pselect`
> Add pselect syscall as a wrapper of kevent

- include/aarch64/pmap.h
- include/mips/pmap.h
- include/riscv/pmap.h
- include/sys/_pmap.h
- sys/gen/pmap.c
Optimizing `pmap_protect` to traverse pmap structure effectively instead of looking up every pte starting from root.
The `pmap_protect_walk` function is called recursively at each pmap level. On the last level it modifies the protection of pte.
Below I provide some statistics about function calls created using KFT, to show that this change really matters.
**Before**
```
function: count avg time
vm_map_clone:   146   158477
vm_page_fault:  3910     7901
pmap_protect:  1041    19849
```
**After**
```
function: count avg time
vm_map_clone:   146    64040
vm_page_fault:  3668     7554
pmap_protect:  1041     6674
```
> Improve pmap protect
