- startup.S
> Removed a conflicting _estack definition

- Makefile
- include/asm.h
- include/global_config.h
- init_caches.S
- init_cp0.S
- init_gpr.S
- init_tlb.S
- startup.S
> Implement proper MIPS microAptiv CPU initialization

- Makefile
- include/common.h
- include/queue.h
- include/runq.h
- include/thread.h
- runq.c
> Implement runq

- Makefile
- include/pager.h
- include/vm_map.h
- interrupts.c
- pager.c
- vm_map.c
Code needs some refactoring and the interface for most of functions could be better, but in my opinion this is ready for merge with master. After this I'd like to implement some of paging on demand. But this needs pager (I already read chapter about pagers in FreeBSD book, to be honest I really like this solution), and is better to be implemented in other pull request/commit. This is also necessary to make sure everything works.
> Add vm_map

- callout.c
- clock.c
- context-mips.S
- context.c
- include/context.h
- include/sched.h
- include/thread.h
- intr.S
- sched.c
- thread.c
Closes https://github.com/cahirwpz/mimiker/issues/45, https://github.com/cahirwpz/mimiker/issues/39, https://github.com/cahirwpz/mimiker/issues/33.
> Add preemptive scheduling

- include/exception.h
- mips/exc.S
- mips/genassym.c
- syscall.c
@rafalcieslak @coodie Please review hard ;-)
BTW. `vm_map.elf` and `pmap.elf` tests in master branch are broken.
> Implement syscalls from user space. Fix switching routines.

- include/mips/ctx.h
- mips/context.c
- mips/genassym.c
- mips/pmap.c
- mips/switch.S
- sched.c
- sys/vm_map.c
I decided to introduce user space threads, which are in fact one thread processes. This is needed to test execution of recently introduced elf files and good introduction to processes. This will obviously need some changes, but it is a good start.
> User threads switch vm_map spaces

- sys/sched.c
This PR surrounds `sched_switch` and `sched_add` with critical section, in case of turnstiles it sometimes happened that runq was left in undefined state due to races.
> Fix sched_switch and sched_add race conditions

- include/thread.h
- sched.c
- sys/thread.c
- thread.c
As discussed, these minor utilities will simplify implementing some things a lot.
@psie, you may be interested in this.
Unfortunately, this branch also does some formatting fixes.
> Thread IDs and all_threads list

- debug/threads.py
This PR adds kthread command to gdb. Everything should be documented and easy to use.
> Add kthread command

- exec.c
- sys/sysent.c
- user/prog.c
Per request, here is the `sys_exit` stub extracted from #129.
> sys_exit stub

- include/pcpu.h
- include/thread.h
- mips/context.c
- sys/sched.c
- sys/thread.c
This is only a stub. For now thread is marked not to be executed but nothing is cleaned after.
> thread_exit stub

- Makefile
- include/common.h
- include/linker_set.h
- linker_set.c
- linkset.c
- malta.ld
Very simple and straightforward implementation of linker sets, based on DragonFly BSD.
ref: #168
> Linker sets

- include/turnstile.h
- include/vnode.h
- sys/dev_uart.c
- sys/mutex.c
- sys/sysent.c
- sys/thread.c
- sys/turnstile.c
- sys/uio.c
- sys/vfs.c
- tests/vfs.c
Per [your request](https://github.com/cahirwpz/mimiker/pull/152#issuecomment-266525520), I've extracted from #152 as much as possible.
> Various fixes extracted from #152

- Makefile
- include/bitstring.h
- include/cpio.h
- include/interrupt.h
- include/mutex.h
- include/physmem.h
- mips/intr.c
- mips/pci.c
- mips/tlb.c
- sys/devfs.c
- sys/exec.c
- sys/malloc.c
- sys/physmem.c
- sys/rwlock.c
- sys/sched.c
- sys/sleepq.c
- tests/exec.c
- tests/exec_fd_test.c
- tests/exec_misbehave.c
- tests/syscall.c
I need to `make format` my new changes, but that introduces a lot of formatting fixes for old sources - so as the first step I've formatted all sources currently in master.
> Formatted sources

- include/ktest.h
- include/rwlock.h
- sys/rwlock.c
- tests/Makefile
- tests/rwlock.c
Created few sanity checks for rwlocks and fixed bugs in rw_try_upgrade and __rw_assert.
> rwlock tests and bug fixes

- sys/callout.c
- sys/ktest.c
- tests/callout.c
~I created this PR only so that I can debug travis test results, please ignore it for now.~
> Various callout fixes

- run_tests.py
Useful when running tests on a local machine.
> Implemented `--ovpsim` option for ./run_tests.py

- sys/filedesc.c
> Fixed fdtab_copy

- sys/thread.c
Wrapped `thread_join` into a critical section.
> Fix for #227

- run_tests.py
Very useful for running tests on a local machine.
> Infinite testing mode

- include/sbrk.h
- sys/Makefile
- sys/exec.c
- sys/sbrk.c
- sys/sysent.c
Per [request](https://github.com/cahirwpz/mimiker/pull/228#discussion_r109307823) in discussion of #228.
> Moved sbrk interface to sbrk.c

- include/common.h
Formatting fix after last commit. Actually fixing travis to see if it detects issues on other pull requests
> Formatting fix

- include/filedesc.h
- sys/filedesc.c
- tests/Makefile
- tests/resizable_fdt.c
Improved current implementation of file descriptor table so that it can grow (but isn't able to shrink yet), as requested in #247
> Implemented resizable file descriptor table

- include/stdc.h
- stdc/Makefile
- stdc/stdlib/rand.c
- sys/ktest.c
@czapiga Is that would you would like to have to finish #305 ?
@rafalcieslak I guess we can replace `rand` from `ktest.c` with this PRNG. Should I do it?
> Import pseudo-random number generator from *BSD

- user/newlib/Makefile
This helps a lot when debugging problems like #321.
> Compile newlib with debugging symbols

- sys/dev_cons.c
> Fixed dev_cons_read

- tests/initrd.c
> Fixed binary junk during ramdisk test

- script/show-sysinit.py
Requires `graphviz` package.
Usage (in main mimiker directory):
`python3 script/show-sysinit.py | dot -Tpng > a.png`.
> graph visualisation of system initialization process

- .gdbinit.template
- debug/kdump.py
- debug/ktrace.py
- debug/mutex.py
- debug/ptable.py
- debug/threads.py
- launch
- launcher/__init__.py
- launcher/common.py
- launcher/debuggers.py
- launcher/simulators.py
Please review it quickly. I'd like to merge it ASAP.
> Fix PEP8 errors and warnings.

- Makefile.common
- include/common.h
- include/filedesc.h
- include/ktest.h
- include/pmap.h
- include/uio.h
- mips/pmap.c
- stdc/stdio/__format_parser_int.c
- sys/dev_cons.c
- sys/filedesc.c
- sys/ktest.c
- sys/malloc.c
- sys/pci.c
- sys/physmem.c
- tests/linker_set.c
- tests/pmap.c
> Enabled Wextra compilation flag

- launcher/simulators.py
- run_tests.py
This branch enables QEMU instruction counting and makes it the default simulator.
> Fix all problems

- .circleci/config.yml
- .circleci/image/Dockerfile
- user/newlib/Makefile
This change also installs new toolchain based on gcc 6.3.0
> Switch CircleCI build environment to Debian 9.0

- sys/ktest.c
> A typo in sys/ktest.c

- mips/intr.c
- tests/utest.c
- user/utest/Makefile
- user/utest/exceptions.c
- user/utest/main.c
- user/utest/misbehave.c
- user/utest/utest.h
* testing Coprocessor Unusable exception in userspace.
* testing Reserved Instruction exception in userspace.
> Testing Coprocessor Unusable and Reserved Instruction exception in userspace.

- include/pmap.h
- mips/pmap.c
- Add mutex to `pmap_t`
- Synchronize `pmap` operations using mutexes
> Synchronize pmap operations using mutexes

- bin/ls_rec/ls_rec.lua
- bin/lua/init.lua
- bin/lua/lunix.c
* simple `getopt` in Lua for command line parsing
* throw a pair `{[err] = errno, [msg] = sys_errlist[errno]}` instead of just a number
> Implement extra functionalities for Lua to enable #513

- include/proc.h
- include/signal.h
- sys/proc.c
- sys/signal.c
- sys/sysent.c
In response to issue: https://github.com/cahirwpz/mimiker/issues/545
> move do_kill to proc_sendsig

- sys/kern/proc.c
- sys/kern/signal.c
- sys/kern/syscalls.c
This is @cahirwpz 's patch from #general Slack channel.
> Fix pgrp/proc locking issue 

- launch
- sys/kern/main.c
- sys/kern/startup.c
- sys/mips/malta.c
Add option to pass arguments to init program using launch. Everything after --
will be passed as arguments.
Example command:
./launch -d init=/bin/ls -- / /usr
> Pass arguments to userspace programs.

- include/sys/vnode.h
- sys/kern/initrd.c
- Support for lookup of parent node
- Added ino_t to vattr
- Saving vnode refrence in cpio root node
> Improvements and fixes to initrd filesystem

- README.md
- bin/ksh/emacs.c
- bin/ksh/misc.c
- bin/lua/Makefile
- bin/lua/Makefile.patch
- bin/lua/clang-warning.patch
- bin/utest/signal.c
- build/compile.mk
- include/dirent.h
- lib/libc/sys/getdents.c
- lib/libutil/efun.c
Now it's possible to run `make CLANG=1`. Tested with Clang 9.0. All tests pass.
> Compile everything with Clang

- include/sys/vfs.h
- include/sys/vnode.h
- sys/kern/vfs.c
- sys/kern/vfs_syscalls.c
- sys/kern/vfs_vnode.c
Implemented [mkdir](https://netbsd.gw.com/cgi-bin/man-cgi?mkdir+2+NetBSD-current) syscall.
> Implement mkdir syscall

- sys/kern/tmpfs.c
Tmpfs is now able to create/remove files and directories.
> Add remove v-node operation for tmpfs.

- bin/utest/main.c
- bin/utest/utest.h
- bin/utest/vfs.c
- sys/kern/tmpfs.c
- sys/tests/utest.c
Code of #620 had to be rewritten due to being over complicated.
> Add read/write operations for tmpfs.

- include/sys/libkern.h
- sys/libkern/stdlib/strtoul.c
- sys/libkern/string/Makefile
> Fix strntoul implementation

- bin/utest/vfs.c
- include/sys/vfs.h
- sys/kern/vfs.c
- sys/kern/vfs_syscalls.c
Paths with symbolic links in it are now correctly resolved.
> Symbolic links resolving

- include/sys/vfs.h
- sys/kern/vfs_syscalls.c
* Fix function call in vfs_namelookupat routine
* Move repeatedly used code in a single functions
* Clean up vfs_open
> Yet another attempt to clean up vfs_syscalls.c

- sys/kern/sleepq.c
> Fix race between sig_kill and _sleepq_wait.

- sys/mips/pmap.c
check page alignment in `pmap_kenter`
> check page alignment in pmap_kenter

- include/sys/kmem.h
- sys/kern/kmem.c
New functions will be used in tmpfs.
> Split kmem_alloc & kmem_free functions

- config.mk
- include/mips/malta.h
- sys/Makefile
- sys/arm64/Makefile
- sys/mips/Makefile
- sys/mips/malta.c
- sys/mips/start.S
> Rename platform to board.

- sys/aarch64/boot.c
- sys/aarch64/start.S
Create one page in `_boot_data` for stack.
> Remove assumptions about initial stack.

- sys/aarch64/boot.c
Build directly-mapped page table.
`DMAP` will be located at `DMAP_BASE` which is `0xffffff8000000000`.
> Directly-mapped page table for AArch64

- include/aarch64/armreg.h
- sys/aarch64/interrupt.c
Implemented in #743.
- `cpu_intr_disable`
- `cpu_intr_enable`
- `cpu_intr_disabled`
> AArch64 cpu_intr_

- sys/debug/struct.py
> Fix bintime printing

- usr.bin/Makefile
- usr.bin/seq/Makefile
- usr.bin/seq/seq.c
This cs introduce seq (well known command from NetBSD/Linux)
> Import seq from NetBSD

- include/sys/devclass.h
- sys/mips/timer.c
Fix a typo and remove a needless header.
> Tiny changes.

- include/sys/device.h
- include/sys/rman.h
- sys/kern/device.c
- sys/kern/rman.c
- sys/mips/gt64120.c
- sys/mips/rootdev.c
Remove some (for now) unnecessary device and resource fields.
> Simplify drivers interface.

- sys/aarch64/rpi3.c
- sys/aarch64/switch.S
> AArch64 fixes

- include/sys/pci.h
- sys/kern/pci.c
Check the `multiple functions` bit of a device and handle bar size correctly.
> Minor fixes to PCI.

- include/aarch64/plcomreg.h
> Import plcomreg.h from NetBSD

- sys/aarch64/switch.S
Being consistent in _PC_ & _LR_.
> Fix SAVE_CTX.

- sys/aarch64/rootdev.c
Use correct registers for enabling and disabling irq.
> Fix rootdev_enable/disable_irq.

- sys/kern/vfs_syscalls.c
Add check if file given as argument to `cd` command is a directory
> Fix bug in do_chdir

- sys/aarch64/pmap.c
Enable memory translation for EL0.
> User pmap.

- lib/csu/aarch64/crt0.S
Starting procedure for user ELF images.
> Starting procedure for user ELF images.

- include/aarch64/armreg.h
- include/aarch64/syscall.h
- lib/libc/sys/aarch64/sc_error.S
- sys/aarch64/context.c
- sys/aarch64/trap.c
> Syscall handler for AArch64.

- sys/aarch64/context.c
Implement `user_mode_p` for AArch64.
> Implement user_mode_p for AArch64.

- sys/kern/tty.c
If we report an error, the number of bytes read/written is not returned to userspace.
> tty: don't report errors on partial reads/writes.

- sys/kern/vm_physmem.c
We are not able to allocate more pages then `PM_NQUEUES`.
> Typo in vm_page_alloc.

- include/sys/interrupt.h
- sys/drv/rtl8139.c
- sys/kern/interrupt.c
- sys/kern/main.c
Interrupt threads implementation.
> Interrupt threads implementation

- sys/aarch64/evec.S
- sys/aarch64/genassym.cf
Load user context in proper way.
> Load user context in proper way.

- sys/aarch64/context.c
- sys/mips/context.c
Implement `do_setcontext` for _AArch64_.
> Implement do_setcontext for AArch64.

- bin/Makefile
- bin/chown/Makefile
- bin/chown/chown.c
- include/grp.h
- include/pwd.h
- lib/libc/gen/pwcache.c
I added functions:
* `uid_from_user()` 
* `gid_from_group()`
And added implementation for:
* `user_from_uid()`
* `group_from_gid()`
> Port chown program

- lib/libc/gen/pwcache.c
- lib/libc/gen/pwcache.h
Simply copied files `pwcache.c` and `pwcache.h`.
> Get pwcache from NetBSD

- build/build.prog.mk
- usr.bin/su/Makefile
We can specify if program will have set `set-user-id` bit by setting variable `SETUID` in Makefile for that program.
> Allow to set set-user-id bit on userspace programs

- include/sys/pci.h
- sys/mips/gt64120.c
Make definitions in `include/sys/pci.h` compliant with the PCI specification.
> Fix PCI configuration space reading/writing.

- sys/kern/main.c
- sys/kern/malloc.c
- sys/kern/pool.c
- sys/kern/vmem.c
* Manage `vmem_t` and `pool_t` memory with `kmalloc`.
* Create first kernel malloc arena statically.
> Start kernel malloc earlier.

- sys/tests/sleepq_timed.c
The variable `timed_received` is concurrently incremented by multiple threads, so we need to use atomics in order to avoid a race.
> test_sleepq_timed(): fix race on shared variable.

- include/sys/context.h
- sys/aarch64/context.c
- sys/mips/context.c
For [#863](https://github.com/cahirwpz/mimiker/pull/863) and  [#979](https://github.com/cahirwpz/mimiker/pull/979)
> Get program counter from context

- include/sys/ringbuf.h
- sys/kern/ringbuf.c
This function is required by #935.
> Introduce ringbuf_getnb.

- .gdbinit-test
- .github/workflows/default.yml
- include/sys/ktest.h
- launch
- launcher/__init__.py
- run_tests.py
- sys/debug/cmd.py
- sys/kern/ktest.c
- sys/kern/main.c
It's high time for test run not to depend on output from kernel console but rather on gdb behaviour.
> Fully control test-run using gdb.

- include/sys/vm_physmem.h
- sys/kern/kmem.c
- sys/kern/vm_physmem.c
This is a step towards contiguous physical page allocation.
> Allocate list of physical pages.

- sys/debug/ctx.py
> AArch64/dbg: adjust ctx.py to AArch64.

- Dockerfile
- toolchain/qemu-mimiker/Makefile
- toolchain/qemu-mimiker/debian/changelog
- toolchain/qemu-mimiker/patches/fix-virtual-clock-in-gdb.patch
- toolchain/qemu-mimiker/patches/page-table-walk-for-gdb.patch
Seems like 5.2.0 suffers from deadlocks.
> Revert to QEmu 4.2.1

- launch
- sys/aarch64/pl011.c
Basic TTY implementation for pl011.
> tty/pl011: basic TTY implementation for pl011.

- sys/kern/tty.c
Processes in background process groups are restricted from modifying the settings of their controlling terminal.
See e.g. [`tcsetpgrp()`](https://pubs.opengroup.org/onlinepubs/9699919799/functions/tcsetpgrp.html).
> Add background checks to tty ioctls that modify tty settings

- include/aarch64/vm_param.h
- include/mips/vm_param.h
- sys/kern/thread.c
Increase stack size for AArch64.
> thread: increase stack size for 64 bit architectures

- include/dirent.h
- include/sys/input-event-codes.h
- include/sys/input.h
- lib/libc/gen/scandir.c
This PR adds header files and one libc function required by the evdev (#1089). Everything was copied from NetBSD & FreeBSD and left unmodified.
> [evdev 1/3] Add prerequisites for evdev

- sys/aarch64/pmap.c
> aarch64/pmap: fix pmap_kremove

- include/dev/uhci.h
- include/dev/usb.h
- include/dev/usbhc.h
- include/dev/usbhid.h
Present some changes which has arisen during work around #935.
> Update USB headers.

- sys/kern/cred_syscalls.c
Saved uid should be set to new effective uid not to old. [1]
[1] [NetBSD Manual](https://man.netbsd.org/setreuid.2)
> Fix setreuid

- include/dev/usb.h
- include/dev/usbhc.h
- sys/drv/uhci.c
This PR is an outcome of work done around #935 (and #1114).
> USB headers update.

- sys/tests/vm_map.c
The correctness of the test depended on not switching to another process, which can't be guaranteed even if we disable preemption, since a thread in another process might be holding a mutex that we want to acquire. Therefore, it is necessary to store the temporary userspace `vm_map` in the current process, so that it is restored when we switch back.
> Store temporary userspace vm_map in process in paging_on_demand_and_memory_protection_demo()

- toolchain/qemu-mimiker/Makefile
- toolchain/qemu-mimiker/debian/changelog
- toolchain/qemu-mimiker/patches/fix-virtual-clock-in-gdb.patch
- toolchain/qemu-mimiker/patches/gdbstub-stop-on-sigxcpu.patch
- toolchain/qemu-mimiker/patches/page-table-walk-for-gdb.patch
Since we need USB support for Raspberry Pi emulation.
> Update QEMU to 6.0.0

- README.md
That flag doesn't exist anymore.
Signed-off-by: Paweł Jasiak <pawel@jasiak.dev>
> README: remove -D from launch script

- .ackrc
> [tools] update ackrc

- lib/libc/gen/riscv/_setjmp.S
- lib/libc/gen/riscv/longjmp.c
- lib/libc/gen/riscv/setjmp.S
- lib/libc/gen/riscv/sigsetjmp.S
- lib/libc/riscv/genassym.cf
Implementation of nonlocal goto functions for the RISC-V target architecture.
> [RISC-V][libc] Nonlocal goto.

- include/riscv/syscall.h
- lib/libc/sys/riscv/sc_error.S
- lib/libc/sys/riscv/sc_missing.S
libc syscall implementation for the RISC-V target architecture.
> [RISCV][libc] Syscalls.

- lib/csu/riscv/crt0.S
This PR provides an entry point for user ELF images.
> [RISC-V][csu] Entry point for ELF images.

- include/riscv/sbi.h
- sys/riscv/Makefile
- sys/riscv/sbi.c
A supervisor mode RISC-V kernel communicates with its execution environment via Supervisor Binary Interface (SBI). The presented change introduces a kernel library for issuing services defined by the SBI specification.
> [RISCV] Introduce kernel SBI library.

- sys/riscv/mcontext.c
Machine-dependent CPU context management module for RISC-V.
> [RISCV] Machine context management module.

- sys/tests/pmap.c
- sys/tests/vm_map.c
Add support for machine-independent tests.
> [RISCV] Support for MI tests.

- include/riscv/asm.h
- sys/riscv/Makefile
- sys/riscv/genassym.cf
- sys/riscv/mcontext.c
- sys/riscv/switch.S
Context switch implementation.
> [RISCV] Context switch.

- include/riscv/abi.h
- include/riscv/elf_machdep.h
- include/riscv/int_mwgwtypes.h
- include/riscv/mcontext.h
- include/riscv/pmap.h
- include/riscv/pte.h
- include/riscv/types.h
- include/riscv/vm_param.h
Introduce header files for 64-bit RISC-V.
> [RISCV] 64-bit headers.

- sys/drv/simplebus.c
Some buses utilize the `ranges` property to express mappings between bus-relative addresses and parent-relative addresses. This change adds support for the `ranges` property within the `soc` device node.
> [dev] Support for the SOC ranges fdt property

- sys/kern/malloc.c
Remove unused memsz variable from malloc and free routines to prevent
compiler warning.
```
mimiker/sys/kern/malloc.c:229:12: error: variable 'memsz' set but not used [-Werror,-Wunused-but-set-variable]
size_t memsz = reqsz - USEDBLK_SZ;
^
mimiker/sys/kern/malloc.c:258:10: error: variable 'memsz' set but not used [-Werror,-Wunused-but-set-variable]
size_t memsz = bt_size(bt) - USEDBLK_SZ;
^
2 errors generated.
```
> [kern/malloc]: Remove unused variable.

- include/riscv/pmap.h
- sys/riscv/pmap.c
Implementation of the architecture-dependent pmap interface for the RISC-V 64-bit target architecture.
> [RISCV] 64-bit pmap implementation

- build/arch.riscv.mk
- config.mk
- sys/riscv/riscv.ld.in
Add the Sivife Unleashed (`sifive_u`) build target.
> [RISCV] Sifive Unleashed build target.

- sys/kern/kgprof.c
- sys/riscv/Makefile
Add support for all the kernel tools.
NOTE: this change will only work after #1091 is merged.
> [RISCV] Support for kernel tools.

- Dockerfile
- Makefile
- build/tools.mk
* On Mimiker server compilation time went down from 80s to around 55s and sometimes less.
> Speed up compilation with ccache

- .github/workflows/default.yml
- config.mk
- lib/libc/gen/aarch64/_setjmp.S
With this change we finally switch default compiler to Clang.
> Switch AArch64 build from gcc to clang

- sys/drv/evdev.c
The evtest application (#1096) requires the evdev device grabbing feature.
> [dev] Implement evdev device grabbing.

- build/tools.mk
Fix which invocation - cache -> ccache.
> build/tools: s/cache/ccache/

- lib/libc/Makefile
- lib/libterminfo/Makefile
- sys/aarch64/Makefile
- sys/contrib/libfdt/Makefile
- sys/drv/Makefile
- sys/gen/Makefile
- sys/libkern/builtins/Makefile
- sys/libkern/ctype/Makefile
- sys/libkern/stdio/Makefile
- sys/libkern/stdlib/Makefile
- sys/libkern/string/Makefile
- sys/mips/Makefile
- sys/riscv/Makefile
- sys/tests/Makefile
- usr.bin/id/Makefile
- usr.bin/login/Makefile
- usr.bin/su/Makefile
* reorder flags in Makefiles
* add `-Wno-unused-const-variable` for _libterminfo_
> build: flags cleanup

- include/dev/usb.h
- sys/drv/usb.c
We need basic support for USB hubs as on some boards the number of root ports is constrained and we must rely on external hubs to provide additional attachment points.
> [dev] Basic USB HUB support.

- include/dev/usb.h
- include/dev/usbhid.h
- sys/drv/usb.c
Standard USB request for managing HID keyboard LEDs.
> [usb] HID keyboard LED management.

- sys/riscv/pmap.c
There is a cycle between `pmap::mtx` and `kernel_pmap::mtx`. The conflicting scenarios (RISC-V only):
1. We run out of kernel virtual address space and `pmap_growkernel` must be called. This results in `pmap_growkernel_md` being called which first acquires `kernel_pmap::mtx` and then `pmap::mtx`.
2. When entering a new mapping to the user's virtual address space, we must allocate a pv entry from the appropriate pool. However, if the pool happens to be empty, `kmem_alloc` gets called which results in a call to `pmap_kenter`. `pmap_enter` first locks `pmap::mtx`, and then `pmap_kenter` locks `kernel_pmap::mtx`.
The solution is simply changing the acquiring order in RISC-V's `pmap_growkernel_md` implementation.
> [lockdep][RISCV] Fix pmap lock acquiring order.

- .github/workflows/default.yml
The goal of this PR is to conserve our build server capacity.
> [gh-actions] Cancel previous builds if new commit arrives

- include/sys/unistd.h
- lib/libc/gen/errlist.c
- lib/libc/gen/sysconf.c
- lib/libc/gen/usleep.c
This PR introduces some libc changes needed for porting tools from suckless ubase (https://github.com/cahirwpz/mimiker/pull/1371)
> libc changes for ubase tools

- include/sys/poll.h
- lib/libc/sys/poll.c
- lib/libc/sys/select.c
This PR provides `poll` syscall implemented as a wrapper of `kevent` syscall.
> Add poll syscall as a wrapper of kevent

- sys/kern/vm_amap.c
Remove bitmaps from amaps. Actually bitmaps are not needed because we can check if anon is present based by checking if its slot is Null.
> amap: remove bitmap
